### ISSUE TITLE
Conflicted copy error

### ISSUE THREAD

**Issue by HaithamMaya** [standardnotes/forum#1438] opened 2021-11-04 01:34 UTC
**Describe the bug**
Receive a conflicted copy error as I am editing a note in the linux desktop version of standard notes.

**To Reproduce**
1. Create a new notes
2. Start typing. As you type and its saving, I get conflicted copy errors.

**Expected behavior**
Expecting a single note as I am editing a note.

**Screenshots**
Similar to #928 

**Desktop (please complete the following information):**
 - OS: pop-os (linux)
 - Version 3.8.21

**Comment by JaspalSuri** [comment] 2021-11-04 06:14
Hi @HaithamMaya, sorry to hear that; we're looking into what might have caused this. Are you still experiencing this issue by any chance?

**Comment by atombrenner** [comment] 2021-11-04 14:47
I have the same issue with the web version of standard notes. I upgraded yesterday to the pro plan. And now every second keystroke or so creates a duplicate of my note with a "Conflicted Copy" error. It worked for month with the free version, since I upgraded it's no long usable :-(

**Comment by tephyr** [comment] 2021-11-04 15:25
I had this problem occur around the same time as @HaithamMaya's report on Android.  I also *just now* used SN on Linux (installed via snap) and had sync problems when trying to delete the same note that was duplicated when I edited it on Android previously.  It appears that the note is properly saved (and the removal of the duplicate succeeded).

**Comment by p1morris** [comment] 2021-12-02 08:27
I'm having the same issue as OP on 3.9.5 using the Mac OS client. As I was working on one note, I had continual duplicates popping up as a 'conflicted copy'. I saved my error log showed _Failed to load resource: the server responded with a status of 500 ()_. I'll keep monitoring it; but from that error this should be a temporary issue related to the server being down? I'm a paid subscriber and sync to the default SN server.

**Comment by effieeee** [comment] 2022-10-06 16:59
Issue now resolved as per update on [blog](https://blog.standardnotes.com/35571/microupdate-server-status-and-conflicts)

**Closed by effieeee** 2022-10-06 16:59 UTC
Labels: bug
