### ISSUE TITLE
editor missing in linux app

### ISSUE THREAD

**Issue by JediBrooker** [standardnotes/forum#156] opened 2018-02-02 14:34 UTC
Hi, I've installed all the editor extensions on the linux app and they're not appearing. I tried signing out and back in again but this didn't work.

**Comment by mobitar** [comment] 2018-02-02 14:46
The extensions server was down momentarily but is back up now. You can just refresh the app for them to reappear, either by using cmd/ctrl + r, or quitting and reopening the app.

**Comment by JediBrooker** [comment] 2018-02-02 14:50
no such luck. editors still didnt load. ive only got the plain editor available. the editors open fine in the web app.

**Comment by mobitar** [comment] 2018-02-02 15:04
What version of the desktop app are you using?

**Comment by JediBrooker** [comment] 2018-02-02 15:06
2.0.2

**Comment by mobitar** [comment] 2018-02-02 15:07
Can you try upgrading to 2.0.42

**Comment by JediBrooker** [comment] 2018-02-02 15:17
i downloaded from arch user repository. 2.0.2 is the version from that im afraid. i'm not skilled enough in linux to install from source yet.

**Comment by mobitar** [comment] 2018-02-02 15:18
You can download from here: https://standardnotes.org/download/linux

Linux AppImage Instructions:
To run the AppImage file, simply:

chmod a+x standard-notes---.AppImage
./standard-notes---.AppImage

**Comment by JediBrooker** [comment] 2018-02-02 15:20
will that replace my current version or should i remove 2.0.2 first?

**Comment by mobitar** [comment] 2018-02-02 15:46
You should remove it..(sorry about the delayed responses. GitHub is not sending email notifications right away)

**Comment by JediBrooker** [comment] 2018-02-02 15:52
the appimage doesn't install, it's just a binary! i'm not a fan of that at all. can't we get the version in the AUR to update or something?

**Comment by JediBrooker** [comment] 2018-02-02 15:59
in any case, i downloaded and ran the appimage and the editors worked. i guess i'll just hang out for an updated version in the AUR.

**Comment by JediBrooker** [comment] 2018-02-02 16:02
actually i checked out the AUR page: https://aur.archlinux.org/packages/sn-bin/
and it says the source is version is 2.0.42. however when i open the help menu it only says 2.0.2. weird!

**Comment by mobitar** [comment] 2018-02-02 16:59
@JoshuaRLi any idea?

**Comment by JoshuaRLi** [comment] 2018-02-02 17:24
@JediBrooker Hi, I'm the maintainer for `sn-bin` on the AUR.

I can't reproduce what's going on in your side. If you read the `PKGBUILD`, the 2.0.42 AppImage is downloaded as `/usr/bin/standard-notes`. Try removing your 2.0.2 installation, your shell is likely resolving `standard-notes` to the wrong executable.

**Comment by JediBrooker** [comment] 2018-02-02 17:59
ahhh, installed the old standard notes app from AUR: https://aur.archlinux.org/packages/standardnotes-desktop/

you should remove it @JoshuaRLi

**Comment by JediBrooker** [comment] 2018-02-02 18:15
oh, except i installed it from AUR and it didn't create a desktop entry to add to kde menu...

**Comment by JoshuaRLi** [comment] 2018-02-02 18:26
@JediBrooker I can't remove someone else's AUR package, but I did help flag it out-of-date. I'll submit a request for deletion, but no guarantees it will go through.

**Closed** 2021-01-10 04:22 UTC
