### ISSUE TITLE
Bulk changes of editor type to plain text[Help Wanted]

### ISSUE THREAD

**Issue by few4i** [standardnotes/forum#3188] opened 2023-07-16 10:28 UTC
**Describe the issue**
Somehow the default note type for most/all of my notes was changed to plain text.  I have hundreds of notes so a bulk change of the editor type.  In the account menu, it has my active subscription information, but the drop down menu for "new note defaults" says I need to upgrade my account.  But I have a subscription that is active.

I've tried signing out of workspace, and emptying the cache on the browser. 

My other installations in iOS seem to be fine.

I suppose I can backup from a previous version, but it looks like the program itself is confused about whether I have a subscription or not.  

**To Reproduce**
I can't reproduce the "new notes default" in iOS.  But this editor change was perpetuated everywhere.

**Expected behavior**
I write all of my notes in markdown and hope that the editor stays the same 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser:  Chrome  114.0.5735.199

**Comment by affe42** [comment] 2023-07-16 11:43
Similar problem here. I have thousands of older notes now reverting to plain text. The issue started a few revisions ago, so it seems to be some change/bug in devs code. Going through malformed old notes one by one is not an option. Changing the "New Note Defaults"-option to Rich Text does not affect them.

I have to say that I'm dissappointed about the quality of SN updates lately.

**Comment by NotSteveAtGithub** [comment] 2023-07-16 18:12
Similar impact here.  Upgraded from Mac 3.162.8 to 3.166.9, and most of my notes changed to plain text.  Thankfully I was able to change the note type for all my notes (I have less than 100 notes) back to their original types.

**Comment by urnammu** [comment] 2023-07-17 00:32
I also am experiencing this issue. Upgraded to 3.166.9 on a MBP that is running Ventura 13.3.1. I have hundreds of notes, most of which reverted to plain text. Oddly, those notes created within the past few months (<4 months) did not change to plain text. There are too many to switch back to Rich Text by hand.

**Comment by effieeee** [comment] 2023-07-20 17:33
Hi all, there was a notable issue with subscription recognition for certain accounts, and we recently [pushed a fix](https://github.com/standardnotes/app/pull/2361) for this. Please make sure that you update your apps to v3.167.0 or later, and you may also try signing out and signing back into your accounts after updating the apps.

If you continue to experience issues on the latest version, please send us an email at help@standardnotes.com using your Standard Notes account email 🙏

**Closed as completed by effieeee** 2023-07-20 17:33 UTC
Labels: help wanted

**Comment by affe42** [comment] 2023-07-21 18:26
The problem is **not** fixed with 3.167.2 !

Still thousands of old notes showing Plain Text instead of Rich Text (tested with latest WebApp as well, no difference).

I don't see this is related to subscription recognition, as all editors have otherwise worked normally and no error messages about subscription status.

**Comment by effieeee** [comment] 2023-07-22 15:24
Hi @affe42 , in this case, you also appear to be experiencing the issue described in #3197 . Please check my [comment](https://github.com/standardnotes/forum/issues/3197#issuecomment-1646606543) on that issue for more steps you can try on your end!
