### ISSUE TITLE
Android, wrong versioning dates

### ISSUE THREAD

**Issue by pinpontitit** [standardnotes/forum#1747] opened 2022-07-17 14:44 UTC
Hi

On Android:
If I delete some text in a note,
then go to the History of that note ( to check all the past modifications and versions),
its written that the last deletion of some text (which I just did today) was done 3 days ago.
So, for example, modifications on 17/07/2022 are labelled 14/07/2022.
And there's no newer modif than 14/07.

Of course the date on my phone is good.

Why ?
Is it a bug or misconfiguration ?

Thanks

**Comment by myreli** [comment] 2023-02-23 00:56
Sometimes when there is an active session that wasn't saved to history yet it doesn't show in the Note History panel. Or at least I wasn't able to reproduce it now. So it seems like this issue has been fixed in recent versions since the new mobile experience launched, so I'll close it. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed as completed by myreli** 2023-02-23 00:56 UTC
