### ISSUE TITLE
Checklist notes crash the whole app on iOS after latest update

### ISSUE THREAD

**Issue by adworacz** [standardnotes/forum#2185] opened 2022-10-12 20:19 UTC
**Describe the bug**
Checklist notes crash the iOS app. 

**To Reproduce**

update to the latest iOS app version. Open an existing checklist note. Watch it crash. 

**Expected behavior**
App does not crash when opening checklists. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2022
 - OS: ios 16
 - Version 3.41.10

**Additional context**

**Comment by twoprops** [comment] 2022-10-13 00:41
Came here to post this. 

The latest update to SN opens without problem, but crashes if I try to view a checklist note.

A crash also occurs if I try to change the Note Type of an existing note to checklist. The format changes (as viewed on other devices) but the note can no longer be opened by the iOS app without crashing. Force-quitting the app and restarting the phone do not correct the problem.

iPhone SE second generation
iOS 16.0.3
SN version 3.41.10 (237)

No problems with Android, macOS desktop, or web app opening the same notes.

**Comment by homberger** [comment] 2022-10-13 14:30
I am affected by this bug too. App crashes if note type is markdown, even without checklists.
I am using an iPhone SE 2, too. Maybe only this device with iOS 16.0.3 is affected?

**Comment by homberger** [comment] 2022-10-13 14:37
@adworacz @twoprops 
Are you using any self hosted components?

**Comment by twoprops** [comment] 2022-10-13 15:33
Can confirm, "basic markdown" notes do the same crashing thing. I'm not self-hosting anything at this point.

**Comment by twoprops** [comment] 2022-10-13 16:11
I just tried to open a "secure spreadsheets" note and got the same crash, so I tested with "rich text", "alternative rich text", "code", and "markdown." At this point, it looks like the problem occurs loading *any* editor other than plain text.

**Comment by twoprops** [comment] 2022-10-13 18:16
You might be right, @homberger , that the problem is limited to the iPhone SE and/or iOS 16. I just downloaded the update on an old iPhone 6s+ running iOS 15.6 and don't see the problem. Weird if it's SE-specific, but that would explain how it got past testing.

**Comment by adworacz** [comment] 2022-10-13 21:19
> @adworacz @twoprops
> Are you using any self hosted components?

Nope, no self hosting here

**Comment by edwagner** [comment] 2022-10-14 03:06
Version 3.41.10 crashes for me when opening a markdown note (but not plain text) on an iPhone Xs running iOS 15.6.1. However after switching to the new mobile experience it all worked fine.

**Comment by effieeee** [comment] 2022-10-14 13:04
As @edwagner mentioned, the new mobile experience loads all note types properly! I should also note that the new UI will definitely be replacing the old UI in the coming updates, so please do check it out, and just let us know any feedback you have on the new UI as we continue to work on it as well! 🙏

**Comment by twoprops** [comment] 2022-10-14 17:09
@effieeee
> As @edwagner mentioned, the new mobile experience loads all note types properly!

Not quite. Here's what one of my checklists looks like after enabling the new UI.

![IMG_4813](https://user-images.githubusercontent.com/4120679/195903122-836d8286-6bfc-407b-83c2-f9a53ef68e44.PNG)

**Comment by CdtDelta** [comment] 2022-10-14 21:50
Looks like this may be an overall issue with the Alternative Rich Text editor and the mobile version. I have an iPad running version 3.41.10, a Samsung S22 Ultra running 3.41.10 (3002237), and a Samsung S7 tablet running 3.41.10 (3002237). All three crash if I open any note set up with the ART editor.
One other interesting related item, on my S7 tablet, when I opened a note to test just now, it loaded it initially in the Plain Text format, and the note loaded fine. As soon as I changed it to the ART editor, it crashed.

On the Android devices, switching to the new mobile format loaded the ART notes just fine. However, on my iPad, the application crashes immediately after logging in so I can't switch it there. The only way around it was to remove the app from my iPad, reinstall it, then before logging in to my account switching to the new mobile format and THEN log in.

**Comment by effieeee** [comment] 2022-10-15 13:55
@twoprops Hmm, I managed to find another user that was encountering this with checklist notes, though to compare your cases, I wanted to ask if this is the only checklist note you have on your account? If so, can I ask you to create another checklist note, then verify if the issue persists?

**Comment by janikarki** [comment] 2022-10-15 17:21
My wife and I have the same issue on Android with at least Checklist and Basic Markdown notes. Crashes when I try to open a note of these types. If I try to create a new note, it crashes when I change the note type. 3.41.10 (3002237)

**Comment by twoprops** [comment] 2022-10-15 18:05
@effieeee I have more than one checklist note, but the other one seems to work correctly under the new UI. It crashes under the old UI. Also possibly related, I have seen a few other anomalies since switching to the new UI. One is this at startup (intermittently):

![IMG_4818](https://user-images.githubusercontent.com/4120679/196001505-1f8c95dd-9665-4144-9032-3721ae604e67.PNG)

The same slip pops up occasionally after authentication, with the note showing in the background.

And once, attempting to look at a checklist note, I got:

![IMG_4817](https://user-images.githubusercontent.com/4120679/196001561-6a3eceb5-1c48-4877-b6ba-64b9ce1f3cf5.PNG)

Yes, it's a completely blank screen. The only way to get out of it was to press the home button, then force-quit the app and re-start it. So I think the new UI might not be quite ready for prime time yet, though it beats having the app crash when trying to view a formatted note.

**Comment by twoprops** [comment] 2022-10-16 19:42
I've installed the latest iOS update, 3.43.5 (249), and with the new UI it seems to resolve the checklist display anomaly as well as several other strangenesses (asking for my password randomly, for example). I wanted to see if it fixed display of styled notes in the Classic UI, but when I chose to change back to Classic UI, it stayed with the New Mobile Experience even after restart.

**Comment by chengp3** [comment] 2022-10-17 17:14
Yes as others have noted, Opting into the new experience in the settings menu solved the issue for me! As an aside, the new UI looks absolutely gorgeous and much more functional than previous. Cheers.

**Comment by effieeee** [comment] 2022-10-17 17:37
@twoprops Good to hear that the last update addressed a lot of the issues you were seeing 🙏Actually, the old UI was disabled on this version as well, so you won't be able to switch back to it here, but we're steadily working on the new UI as well to better meet your expectations 🙏

I'll be closing this now, but please feel free to open other issues if you have new reports!

**Closed as completed by effieeee** 2022-10-17 17:37 UTC
Labels: bug
