### ISSUE TITLE
shared between other standardnote user

### ISSUE THREAD

**Issue by whitetornado** [standardnotes/forum#333] opened 2018-10-06 17:23 UTC
is it possible to share a  note (encrypted) with a other note user(s) ??
as a note is updated, other user can see the updated note etc.. etc..

**Comment by mobitar** [comment] 2018-10-08 13:44
No, not presently. Not encrypted at least. You can use Listed to share unencrypted notes. Perhaps in the future Listed will be updated to support encrypted sharing.

**Comment by whitetornado** [comment] 2018-10-08 14:09
ok,but can be customized? when yes, who can i contact for this??

**Comment by mobitar** [comment] 2018-10-08 14:43
This doesn't exist yet. Just an idea.

**Comment by tmikaeld** [comment] 2019-08-18 10:02
Any update on this? I get that we can list it, but can't it be encrypted using password that's unlocked on the client-side? This way we could collaborate somewhat.

My team is currently using Notejoy and are looking to switch.

**Comment by TheodoreChu** [comment] 2021-01-11 04:00
Closing this because it's a duplicate of https://github.com/standardnotes/forum/issues/52

**Closed by TheodoreChu** 2021-01-11 04:00 UTC
Labels: duplicate, enhancement
