### ISSUE TITLE
Version 2.1.1 on Windows, Cursor moves after auto save

### ISSUE THREAD

**Issue by rmccrary** [standardnotes/forum#169] opened 2018-02-28 19:21 UTC
In simple todo extension, press space on a todo line, what for 5 sec and cursor disappears
In Plus Editor extension, press space, what 5 sec and cursor jumps to top of file.

Please reproduce and let me know of a workaround until it can get fixed.

**Comment by mobitar** [comment] 2018-03-01 16:27
Hey @rmccrary, I'm not able to reproduce either of these issues. Do you recall when you installed these extensions? Was it recent, as in the last month, or maybe a few months ago?

It's possible you have old versions of the editors. Can you try uninstalling, and reinstalling each editor, and see if the issue persists?

**Comment by SirYggdrasil** [comment] 2018-03-06 21:33
I have the exact same issue. Using version 2.1.21, I have a recent version of the Plus Editor extension (Summernote 0.8.8), and I've tried CTRL-C and uninstalling the extension and installing it afterwards.
The same issue exists: After having written for some seconds, the cursor without warning jumps by itself to the start of the note text (like hitting CTRL-HOME)

**Comment by rmccrary** [comment] 2018-03-06 22:39
It still occurs for me today with program and all extensions auto updated. 

When I am back to my computer I will try uninstalling all extensions. Then installing one extension at a time and recording the order that I add them.  I will test after each new extension and report my findings.

**Comment by mobitar** [comment] 2018-03-06 23:56
Any chance anyone can post a video capture of it? Also, what are your network conditions like? And are you signed in to an account, or using the app offline?

**Comment by rmccrary** [comment] 2018-03-07 03:53
I am using the app offline. If I uninstall all extension then just install the Simple Task Manager I see the same problem.  


-----Original Message-----

**Comment by SirYggdrasil** [comment] 2018-03-07 13:52
I've attached a zip with a captured video now (using Windows 10 Game DVR). It shows the cursor jumping to the beginning of the note text on two occasions. If you need more do tell.
I'm also using the app offline, have never signed in to an account. My network is cabled through Ethernet, from a fiber optics provider (300/300 Mbps).

[Notes 07-03-2018 14_42_21.zip](https://github.com/standardnotes/forum/files/1789327/Notes.07-03-2018.14_42_21.zip)

**Comment by mobitar** [comment] 2018-03-07 15:00
Ah interesting, it seems it has to do with being offline. Was able to replicate it..investigating.

**Comment by mobitar** [comment] 2018-03-07 15:55
Ok, should be fixed in v2.1.22. I haven't pushed it out yet, but you can get it here: https://github.com/standardnotes/desktop/releases/tag/v2.1.22

Please confirm if this fixes the issue for you.

**Comment by rmccrary** [comment] 2018-03-07 16:13
I no longer see the cursor jumping problem when offline.  I also don't see (after a quick use) any negative affects of the change online or offline. Looks good.

Thanks,
Rex

-----Original Message-----

**Comment by SirYggdrasil** [comment] 2018-03-07 17:07
No jumping cursor here either. Looks like it is fixed. Great. :)

**Comment by mobitar** [comment] 2018-03-07 17:10
Ok cool :)

**Closed** 2021-01-10 06:12 UTC
