### ISSUE TITLE
A way to archive notes

### ISSUE THREAD

**Issue by skrizzles** [standardnotes/forum#228] opened 2018-06-07 21:55 UTC
This isn't an issue, but I would _love_ a way to archive notes.

**Comment by mobitar** [comment] 2018-06-08 16:53
You can already do this: 
<img width="300" alt="screen shot 2018-06-08 at 11 53 18 am" src="https://user-images.githubusercontent.com/3277844/41170592-8e3036da-6b12-11e8-962a-0744e6091cf8.png">

**Comment by ejohn** [comment] 2018-07-23 19:05
I am unable to archived notes in the search results. Is this expected behavior? Also, when using the folders extension, archived notes are not visible at all.

**Comment by mobitar** [comment] 2018-07-24 13:52
@ejohn searching applies only to the currently selected tag/view. If you want to show archived notes in the list, click Options (in the Notes list panel), then toggle "Archived Notes" in Display.

To get archived notes to appear in Folders, click + to add a top level folder, then paste in `!["Archived", "archived", "=", true]`. These are known as smart tags. Documentation on them is coming soon.

**Comment by ejohn** [comment] 2018-07-24 16:00
@mobitar Thanks so that shows up under "Views" in the folder list. And it still does not let me search both archived and un-archived at the same time. I guess I have to create another view with All Notes and select that while searching?

**Comment by mobitar** [comment] 2018-07-24 18:33
You can view archived and unarchived at the same time via the display options:

<img width="296" alt="screen shot 2018-07-24 at 1 32 53 pm" src="https://user-images.githubusercontent.com/3277844/43158749-1739c0ca-8f46-11e8-864f-1bc831dd305e.png">

**Comment by mobitar** [comment] 2018-09-14 13:42
On mobile you can only view archived notes as a dedicated view (from the Filter options). No way to view them inline yet, but we might add similar Display options to mobile at some point in the near future.

**Comment by ryanpcmcquen** [comment] 2018-09-14 16:27
@mobitar, ideally I just want search to always search _all_ notes, if that was an option I wouldn't need separate display options.

**Comment by mobitar** [comment] 2018-09-15 12:36
Hmm true, maybe search should do that. I'll add this to the backlog.

**Comment by TheodoreChu** [comment] 2021-01-10 06:55
I'm closing this issue because searching within archive notes is available in the recent app version (v3.5+). Please comment if you have anymore issues.

**Closed by TheodoreChu** 2021-01-10 06:55 UTC
