### ISSUE TITLE
[Help Wanted] Import from Evernote

### ISSUE THREAD

**Issue by kahomono** [standardnotes/forum#1226] opened 2021-01-29 12:11 UTC
**Describe the issue**
Created a 71MB ENEX file.  EverNote-to-SN conversion tool drops all the content.

**To Reproduce**
1. Go to 'https://dashboard.standardnotes.org/tools'
2. Click on 'Browse' by the Evernote section
3. Select my ENEX
4. Receive evernote-to-sn file with literally no content
Here's the entire file
```
{
  "items": [
    {
      "uuid": "8864208e-8ddc-4c09-9840-23d9daf5da76",
      "content_type": "Tag",
      "content": {
        "title": "evernote",
        "references": []
      }
    }
  ]
}
```
**Expected behavior**
Expected my few hundred notes.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser Firefox
 - Version 78.7.0esr

**Comment by JaspalSuri** [comment] 2021-01-30 10:19
Hi @kahomono,

I'm afraid that I wasn't able to reproduce this issue in both Firefox ESR and Chromium, but I'll look into it further. Please open the developer tools within your browser by right-clicking anywhere on the page, click **Inspect Element**, and then click on the **Console** tab. Please run the converter again and post a screenshot of any errors that appear in the **Console** tab.

If you could answer the following questions to help us reproduce the issue, we find it quite helpful: 
- Given that there isn't an official Evernote client for Linux distros yet, which client (and OS) did you use to export your notes?
- Are you using Evernote Premium/Business?
- Do you have an estimate of how many tags you have saved? 
- Are you exporting the notes from multiple notebooks into one file? If so, how many notebooks are you using? 
- For notes that contain attachments, how many attachments do they contain on average? 
- What types of files are typically attached?
- If you export fewer notes at a time and use the converter, do you run into the same issue?

**Comment by kahomono** [comment] 2021-01-30 10:25
![Screenshot at 2021-01-30 05-24-20](https://user-images.githubusercontent.com/20188009/106353847-884baf80-62bb-11eb-9370-b96f5fd8f805.png)

**Comment by kahomono** [comment] 2021-01-30 10:27
* I have Evernote running in a Windows 10 VM, which is what I used.
* Past 24 hrs
* No, free
* I don't use tags much at all.  Maybe... five?
* Four notebooks
* Zero or one
* Photos
* Have not tried that yet

**Comment by kahomono** [comment] 2021-01-30 10:32
BTW I disabled my ad-blocker but it was still unable to load the scripts "script-src" and "font-src"
And I got the same result in my output file.

**Comment by JaspalSuri** [comment] 2021-01-30 10:40
Thanks for the update and for answering my questions! I'll use that information to help recreate a similar ENEX file for testing. 

>BTW I disabled my ad-blocker but it was still unable to load the scripts "script-src" and "font-src". And I got the same result in my output file.

That shouldn't matter, as I saw the same error in Firefox and was able to run the export successfully. Thanks for doing that anyway!

**Comment by myreli** [comment] 2023-02-21 15:29
Since this issue was opened SN has changed, including its [importer](https://standardnotes.com/help/10/how-can-i-import-my-notes-from-evernote). It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed by myreli** 2023-02-21 15:29 UTC
Labels: help wanted
