### ISSUE TITLE
[Help Wanted] FileSafe: Can't create new Keys

### ISSUE THREAD

**Issue by Tonbery7** [standardnotes/forum#1131] opened 2020-11-04 18:54 UTC
Hello,

i can't create a new Key in the FileSafe extension. When i try to create a key, i get the following message (popup):

"The extension FileSafe is trying to save an item with type SN|FileSafe|Credentials, but that item does not exist. Please restart this extension and try again."

I recently setup a self-hosted sync-server (Docker) behind a HA-Proxy. General syncing of notes works, so do other extensions (Editors, Folders, Quick tags). 
I tried the Web-App and the Windows-App and the error happens with both.

I had a look at the developer-tools, but i can't see any requests to the sync-server or console-messages after clicking on the "Create New" Button under Keys.

I tried to uninstall/install the extension, but that didn't help.

Versions:
Desktop-App: 3.5.4
FileSafe: 2.0.10
Sync-Server: 3.10.11

I don't believe it's a bug with the server or the apps, because i tried everything before i setup a self-hosted server and it worked. Including an integration of my Nextcloud-Server as FileSafe storage. 
So it seems to be some kind of problem with my setup. I just don't have a clue regarding the cause.

Hope you can help, thanks in advance!

**Comment by JaspalSuri** [comment] 2020-11-05 12:50
Hi @Tonbery7,

We've received a couple of reports regarding this issue but haven't been able to reproduce it yet. I will add this to our report and hopefully the additional details will help us narrow the root cause of this issue.

> Including an integration of my Nextcloud-Server as FileSafe storage.

If you have any insight on how to successfully integrate FileSafe with NextCloud, some users [here](https://github.com/standardnotes/syncing-server/issues/132) might appreciate it. 🙂

**Comment by Tonbery7** [comment] 2020-11-05 13:04
Hello @JaspalSuri,

i'm a software-developer myself, so i would be happy to help if there is anything i can do to analyse this issue!
I could try running the desktop-app from source and see if i can find anything that way?

**Comment by JaspalSuri** [comment] 2020-11-05 13:14
We really appreciate it! I think there might be a simple fix to this, as I was able to reproduce the issue and noticed that it affects the mobile app as well. There doesn't appear to be any errors provided in the console log, for some reason, so it might be a server-side issue (as you've suspected). I've reached out to our backend dev team and will get back to you when I hear back (to save you time 🙂 ).

**Comment by Tonbery7** [comment] 2020-11-05 13:58
So, i testet a bit more and im pretty sure the desktop-app (or the app's in general) are the cause. 
I testet with desktop-app v3.4.10 and it worked using the current FileSafe-Extension (v2.0.10) in offline mode; so without sync-server.

The error starts appearing with any desktop-app since v3.5.0-beta10

Also, i noticed a difference with the permissions the FileSafe-Exentsion askes for. 
With v3.4.10 i get the permission-popup's as follows:

1. FileSafe would like to interact with your FileSafe credentials, FileSafe files, and FileSafe integrations.
2. FileSafe would like to interact with your working note.

But with any v3.5.x i get this:

1. FileSafe would like to interact with your FileSafe credentials, FileSafe files, and FileSafe integrations.
2. FileSafe would like to interact with your working note.
3. (After click on FileSafe bar in note) FileSafe would like to interact with your FileSafe credentials, FileSafe files, and FileSafe integrations.

I think something with the permissions the FileSafe-Extension asks for goes wrong since v3.5.x of the app's.

**Comment by JaspalSuri** [comment] 2020-11-06 09:23
Thank you so much for taking the time to test things further! A fix has been applied to the mobile (v3.5.3) and desktop/web (v.3.5.6) apps. Can you confirm this on your end? 🙂

**Comment by Tonbery7** [comment] 2020-11-06 10:11
Hello,

i can confirm that the problem is resolved on my end! I testet it with my self-hosted sync-server and successfully integrated it with my own Nextcloud-Server.
I also left a comment regarding the integration of FileSafe & Nexclout-WebDAV [here](https://github.com/standardnotes/syncing-server/issues/132).

**Comment by JaspalSuri** [comment] 2020-11-06 12:57
That's great to hear! Thank you for letting us know and thanks for taking the time to leave a comment there!

**Comment by myreli** [comment] 2023-02-15 14:32
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed by myreli** 2023-02-15 14:32 UTC
Labels: help wanted
