### ISSUE TITLE
How to disable spell checker

### ISSUE THREAD

**Issue by ruffson** [standardnotes/forum#210] opened 2018-05-01 06:30 UTC
In the mac app for example, how can I disable the spell checker?
I was looking in the menus and settings but haven't found a way so far.

**Comment by mobitar** [comment] 2018-05-02 15:05
Hey @ruffson, you can disable the spellchecker via the "Menu" dropdown in the editor pane under the note title: 

<img width="302" alt="screen shot 2018-05-02 at 10 04 44 am" src="https://user-images.githubusercontent.com/3277844/39531193-427fa188-4df0-11e8-9471-8a00820c8769.png">

(Ensure the plain editor is in use so you can see this option)

**Comment by mobitar** [comment] 2018-05-06 17:38
Reopening for visibility

**Comment by miltersen** [comment] 2019-10-21 07:57
Hi. Even though Spellcheck is off in the app, it's still running. I have red lines under most words (I use Danish and English) and there is no way to turn it off. Before MacOs Catalina I was able to turn it off systemwide with a mv command. After Catalina update, the red lines are back rendering Standard notes almost useless. The mv command doesn't work anymore, so we really need a spelling and grammar menu in Edit, so we can turn it off/change the language etc.

**Comment by mobitar** [comment] 2019-10-22 17:23
Which editor is this with?

**Comment by miltersen** [comment] 2019-10-24 06:09
It was the Plus editor, but it seems okay now, with the new update 3.0.18. Cheers.

**Comment by laconic144** [comment] 2020-06-05 11:27
Hi, I'm back, and so are the red lines under many words in my notes. I think It began again around a month ago. So the issue was gone between the above-mentioned update, and recently. 

Could something be done about this issue?

Allow me to also bring your attention to these two related issues, from the forum.

https://github.com/standardnotes/forum/issues/258
https://github.com/standardnotes/forum/issues/83

Cheers!

**Comment by JaspalSuri** [comment] 2020-06-06 00:27
Hi, I currently can't reproduce any issues with being unable to disable the Spellchecker [via the menu option](https://github.com/standardnotes/forum/issues/210#issuecomment-386010243). It appears to take a few seconds to fully turn on and off, though.  

What editors are you using with the spellchecker? 

What app are you using and what OS is it running on? 

Thanks for looking into those issues as well!

**Comment by laconic144** [comment] 2020-06-06 05:30
Cheers, happy to help. The red lines are only visible when the plus editor is on, even though the spellcheck is off in the plain editor. I think what many of us Mac users need, is a traditional spelling and grammar option in the edit menu. That's how we - especially multi-lingual folks - control it in all other apps, and are accustomed to this.

**Comment by JaspalSuri** [comment] 2020-06-09 04:34
@baptiste-grob, can you look into this? When using the Plus Editor on macOS (within the desktop app):
- The Spellchecker doesn't appear to point out any typos to me, despite being turned on via the Plain Editor. 
- It says that the Spellchecker isn't available for editor extensions. Perhaps it could say that it needs to be turned on/off via the Plain Editor?. 

> I think what many of us Mac users need, is a traditional spelling and grammar option in the edit menu. That's how we - especially multi-lingual folks - control it in all other apps, and that's what we are accustomed to.

Thanks for the suggestion. I think it might be a limitation based on what can be accessed by Electron-derived apps running on macOS, but I'm sure Baptiste would know more. :) 

([Related release notes](https://github.com/standardnotes/desktop/releases/tag/v3.4.1).)

**Comment by ashutoshsaboo** [comment] 2022-01-15 09:18
Hi @JaspalSuri I'm no longer seeing the "menu" dropdown in plain editor (in the screenshot @moughxyz linked above) for the enable/disable spellcheck option. Has this spell check option been moved somewhere else as part of the re-design (I also checked the 3 dotted menu beside the pin button in the note, couldn't find this spellcheck option there either)? Only 3 menu selections inside a note that I'm seeing are "Editor" (to switch across various editors), "Actions", and "History".

**Comment by moughxyz** [comment] 2022-01-15 13:30
Global spellcheck can be disabled from Preferences > General > Tools. In an upcoming release, you will have the ability to disable spellcheck per note from the note context menu.

**Comment by effieeee** [comment] 2022-10-03 16:32
Closing, already implemented :)

**Closed by effieeee** 2022-10-03 16:32 UTC
