### ISSUE TITLE
Duplicate Extensions after Update

### ISSUE THREAD

**Issue by gbrandel** [standardnotes/forum#1519] opened 2022-01-18 23:45 UTC
I recently updated the application from 3.6.x to 3.9.15 on a few different computers (both Mac and Windows).  After the update, I noticed that I had duplicate extensions installed for all computers but, interestingly, the duplicated extensions were different on each computer.  Also, the "duplications" were not always just two of a given extension.  Sometimes there were three of the same extension or in a few instances, the extension was not duplicated at all.  Very odd.

So I figured that maybe since I keep the application auto-update feature disabled (ironically because updates seem to break things every time) that this update, 3.6.x to 3.9.x, was just too big a jump and messed something up.  So, I did a complete uninstall of the application (including data and configuration folders) and then reinstalled.  To my surprise, the exact same extensions were duplicated in the exact same numbers.

I was curious to see if it might be the case that my device-specific extension configuration (duplicates included) was being synchronized to my account.  To test this hypothesis, I fixed/deleted exactly one of the duplicated extensions (so there was just one instance of that extension remaining) but left all other duplicates in place.  Then I did another complete uninstall and reinstall. After the reinstall and logging back into my account, indeed I did get the exact same last updated configuration -- that is, all of the exact same duplicates except for the one that I had fixed.

Setting aside for the moment whatever bug introduced the duplicate extensions in the first place, I'm confused about what, exactly, is being synchronized to my account.  Is my device-specific extension configuration being synced to my account?  Why would that be needed/desired?  The extensions represent features and functionality that should be part of the core application.  These extensions shouldn't need to be synchronized as they should be installed with the application.  My subscription level will activate the extensions that I am authorized to use and disable the rest.  I really just want my notes data to be synchronized between computers.  I have no need, in fact, do not want, my device-specific application configuration to be synchronized to my account.  If this is what's happening, is there some way to turn off this feature?  If there is no way to disable the configuration synchronization feature, is there some way to reset a bad/corrupt configuration that has already been synchronized to my account?

**Comment by atmoio** [comment] 2022-01-19 15:00
> The extensions represent features and functionality that should be part of the core application. These extensions shouldn't need to be synchronized as they should be installed with the application.

Correct, this is the goal. The reason for the syncing is that we are applying a new system on top of an old one. The new system is mapping subscription features to application functionality. But so that we don't break older versions of the app that don't understand "features", we mapped features to syncable "components", which older versions of the app can understand, and also require overall less refactoring to integrate into the current architecture.

The duplication likely comes from the fact that when we map feature metadata to synced components, we check to see if the component already exists based on its identifier. However, if the existing components haven't been properly decrypted due to whatever reason, we can't inspect its contents, and so we have to create the new components right away. Then, when your data correctly decrypts, you now have double.

The case where data is not decrypted in time is not a reproducible issue I'm afraid, so seems to have something to do with account-specific circumstances involving password or email changes.

In any case, I plan to revisit this soon, to at least do a better job of cleaning up duplicates in the event this happens.

**Comment by myreli** [comment] 2023-02-21 19:10
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed as completed by myreli** 2023-02-21 19:10 UTC
