### ISSUE TITLE
Other language options

### ISSUE THREAD

**Issue by Rickt1569863** [standardnotes/forum#1491] opened 2021-12-13 13:24 UTC
I would like to present an idea, could you add other languages, such as Portuguese and Spanish as options?

**Comment by simetriarota** [comment] 2022-02-01 11:43
Yeah. At the very *least* alternate currencies in the Spreadsheet editor and a date format the rest of the world actually uses.

**Comment by stefan-yas** [comment] 2022-02-03 07:42
Language localization is an excellent idea, however not a priority right now. As for Secure Spreadsheets, for functionalities like these, the [maintainer of the editor](https://demos.telerik.com/kendo-ui/spreadsheet/index) would need to introduce these features so Secure Spreadsheets as a Standard Notes editor can use them as well.

**Comment by myreli** [comment] 2023-02-21 18:53
Closing as a duplicate of https://github.com/standardnotes/forum/discussions/2533.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed by myreli** 2023-02-21 18:53 UTC
