### ISSUE TITLE
Can't login using app on IOS

### ISSUE THREAD

**Issue by supermensa** [standardnotes/forum#2394] opened 2023-01-12 15:39 UTC
**Describe the bug**
When I try to use the app, it briefly shows me my normal files but then it wants me to login again, I access the login via keychain, but after that it just stalls on a white screen. Nothing happens after that. The login screen is also impossible to use manually on a smaller phone, because the keylock icon covers most of the screen (eg. I can't see what I type).

**To Reproduce**
1. Open the mobile app (if logged in, then logout and start over)
2. Wait for app to load
3. Try to login via keychain
4. Try to login by manually typing email and password

**Expected behavior**
I expect it to login normally using keychain.
I expect to be able to see the input fields when I enter information into them

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: IPhone SE
 - OS: IOS 16.0.3
 - Version (can't see, using the latest update as of 12th jan 2023)

**Additional context**

**Comment by I-said-NO-PICKLES** [comment] 2023-01-13 02:36
Same issue. It's not just that you can't see the input field for entering the password (I'm on an iPhone 6S); when you input a character, it immediately switches from the password input field to the e-mail input field. So, not only are the fields obscured by the keyboard, it won't allow the password to be entered properly.

I tried a workaround of inputting a character, then clicking 'Done' (to see the fields properly). Each time I clicked 'Done', I then had to click back into the input field for the Password so that I could enter the next individual character. I had to repeat this process, over and over, to enter the full password. Even then, my credentials weren't accepted. I haven't been able to connect to the server for the past two days, making it impossible to sync.

**Comment by dezzeus** [comment] 2023-01-13 09:19
Same issues with iOS 16.1 on a new iPhone 14 (session somewhat lost while migrating from the previous iPhone X).

As a temporary workaround, I'm using the web app from Safari.

**Comment by larari** [comment] 2023-01-15 15:36
Same issue on iOS 16.1 on iphone 13 after updating the app. No device change. 
Also syncing seems not to work anymore. Changes are only stored locally. 

Log-in work around when cursor always flips back to the email field: 
* select the password field, type only one letter, click done, select tthe password field again, type next letter and so on. A bit annoying though... but it works.

**Comment by tiddesk** [comment] 2023-01-15 18:08
Same issue here. iOS 16.2

**Comment by effieeee** [comment] 2023-01-17 16:39
Hi all, we've noted this and other issues with the current modal windows on the mobile apps, so we hope to fix this in future updates 🙏

**Comment by eqjjh** [comment] 2023-01-18 18:42
I think I'm having the same issue. Unable to see the input screens, and even using the workaround posted by I-said-NO-PICKLES, it does not log me in (but asks for 2FA password which is not set up. Also cannot set up 2FA because of the same issue of not being able to see the box).

Is this issue with premium too?

**Comment by zzzpppzzz** [comment] 2023-02-11 18:57
I think I'm having the same or similar issue. iOS14. App is literally unusable as it is just a blank white screen and nothing else..

I've tried the typical troubleshooting: closing apps, restarting phone, uninstall app, reinstalling app, etc. Still the same issue..

**Comment by myreli** [comment] 2023-02-26 05:07
Hi all! Can you please try the workaround suggested [here](https://github.com/standardnotes/forum/discussions/2906#discussioncomment-5111969)? 

`Settings -> Accessibility -> Motion -> disabled and re-enabled "Reduce Motion"`

It seems like this is caused by the animation in some devices, but the team is still investigating and trying to fix it. For now multiple users had success with this workaround. Let me know if that works!

**Comment by supermensa** [comment] 2023-02-26 10:40
@myreli I had 'Reduce Motion' enabled, switching it on and off seems to have fixed the error of a blank screen coming up sometimes and login failing. Seems to work. Nice catch.

**Closed as completed** 2023-06-09 15:46 UTC
Labels: bug, triage
