### ISSUE TITLE
Feature: Allow custom auto-lock time OR provide more options.

### ISSUE THREAD

**Issue by RonanCodes** [standardnotes/forum#1419] opened 2021-09-22 17:38 UTC
The options are currently very limited:
<img width="419" alt="Screenshot 2021-09-22 at 18 37 47" src="https://user-images.githubusercontent.com/6930753/134393748-917ce735-df38-45c7-be90-6b12c526cfef.png">

Can we add in more options, like 15 minutes, and 30 minutes?
Even better would be a custom option.

**Comment by JaspalSuri** [comment] 2021-09-23 07:23
Hi @RonanCodes, thank you for the feedback! I can see how having more options between the `5m` and `1h` options would be helpful.

**Comment by myreli** [comment] 2023-02-14 18:10
Duplicate of https://github.com/standardnotes/forum/discussions/2542

**Closed by myreli** 2023-02-14 18:10 UTC
Labels: enhancement, desktop/web, duplicate
