### ISSUE TITLE
Feature Request: Shortcut keys

### ISSUE THREAD

**Issue by gwarah** [standardnotes/forum#134] opened 2017-12-11 17:19 UTC
I strongly suggest at least these shortcut keys:

1. General Use Keys
1.1. `[ctrl]+s`: search notes;
1.2. `[ctrl]+n`: create new note;
1.3. `Some [Fn] key`: syncronize;

2. On focus in the first/second panel (browse tags/notes):
2.1. `up/down arrows keys`: to navigate between notes;
2.2. `delete key`: to delete notes;

3. On edition mode:
3.1. `[ctrl]+f`: search a word in current note;

By the way, is there any documentation about this issue?

**Comment by mobitar** [comment] 2017-12-11 17:57
Work was done on keyboard shortcuts but its been postponed for now. It's an often requested issue so there's mention of it probably on every repo.

**Comment by nikolayhg** [comment] 2018-05-07 07:31
+1

**Comment by ndeverge** [comment] 2018-07-25 08:23
+1

**Comment by slambert** [comment] 2019-03-17 14:15
This issue appears to be a duplicate of https://github.com/standardnotes/forum/issues/134

**Comment by gwarah** [comment] 2019-03-17 16:13
This is the #134 thread :)

**Comment by slambert** [comment] 2019-03-17 16:25
😝 

https://github.com/standardnotes/forum/issues/39

**Comment by effieeee** [comment] 2022-10-03 16:02
Tracking here: https://github.com/standardnotes/forum/issues/1511

**Closed by effieeee** 2022-10-03 16:02 UTC

**Comment by atmoio** [comment] 2022-11-21 15:57
Keyboard shortcuts are now available: https://github.com/standardnotes/forum/issues/1511#issuecomment-1322276205
