### ISSUE TITLE
Issue with undo-functionality by pressing ctrl+z 

### ISSUE THREAD

**Issue by odyon01** [standardnotes/forum#223] opened 2018-06-04 20:24 UTC
Hi, today I started using SN more seriously but I came across an issue within the Windows app, which forced me to rewrite some notes again (until I installed the history module, but still took me more effort than wanted).
There's a different behavior when pressing ctrl+z, or going to the Edit menu, and click on Undo. When pressing ctrl+z, multiple steps are undone, instead of just 1 step (like when pressing Undo in the Edit menu). In the worst case, writing the whole note is undone (and redo doesn't work either).

To reproduce: create a new note in the windows app, enable Plus Editor, write 1, hit enter, write 2, hit enter, select 1, write A, select 2, write B, press ctrl+z. Last 2 edits are reversed, instead of just replacing the 2 with B. Redo from the edit menu works correctly.

One small off-topic question/request: Is it possible to use tab-keypress for indenting text (and shift-tab to un-indent), instead of the current ctrl+] and ctrl+[ keypress combinations? It seems to me more natural (or maybe I'm just to used to MS Word :))

Cheers

edit: this also happens in the webUI (except there's no Edit-menu)

**Comment by odyon01** [comment] 2018-06-05 08:15
Ok, I just found out that this is an external plugin you're using, called summernote. I'll add it to their git-issues page as I think it's quite an important issue

**Comment by mobitar** [comment] 2018-06-05 16:57
Yeah, this is an unfortunate issue with Summernote. I solve this with other editors by resetting the history context after setting the initial text, however with Summernote, this isn't possible. I have it on my todo to go back in there and brute force a solution, as I agree, this can be bewildering if you ctrl+z on accident.

**Comment by mobitar** [comment] 2018-06-06 02:18
Ok this should be fixed now with the latest version of the Plus Editor. (Automatic on web, autoupdate via Extensions menu on Desktop)

**Comment by odyon01** [comment] 2018-06-06 15:51
Ok,  just checked, but I have version 1.1.2 installed (which seems to be the latest) of the Plus editor. But still, my 1..2..a..b.. ctrl-z test fails. Also in the webeditor, it fails.

**Comment by mobitar** [comment] 2018-06-06 15:53
I'm not sure what your issue is referring to, but I'm referring to the issue where pressing ctrl+z when selecting a note into the editor removes the note text. If this is something else, then I definitely can't override specific undo behavior of the editor..

**Comment by odyon01** [comment] 2018-06-06 15:58
I created an issue on the summernote git, because I understood this is something related to the internal workings of the editor. 

To reproduce: create a new note in the windows app, enable Plus Editor, write 1, hit enter, write 2, hit enter, select 1, write A, select 2, write B, press ctrl+z. Last 2 edits are reversed, instead of just replacing the 2 with B. Redo from the edit menu works correctly.

Thanks anyways for quickly replying (and fixing something that also seemed serious)!

**Comment by mobitar** [comment] 2018-06-06 17:19
Ah I see, I did just test that out and can confirm. I wonder if it treats replacing text as a unique sort of operation. What's the issue link on Summernote?

**Comment by odyon01** [comment] 2018-06-06 17:23
I added it to the issue of someone else which seemed similar: https://github.com/summernote/summernote/issues/2849

**Comment by realtek8723** [comment] 2018-06-12 10:35
Can you provide some information about the plus Editor (or) Share some links. I also ran in to the same issue here..

**Comment by mobitar** [comment] 2018-06-12 22:13
Here's all the links I can think of:
https://github.com/sn-extensions/plus-editor
https://standardnotes.org/extensions/plus-editor
https://github.com/summernote/summernote

**Comment by andersonbispo** [comment] 2020-11-13 17:32
Hello.

I'm using the summernote version 0.8.18 and I figure out that the summernote is keeping absolutely all actions, including mouse click and word selection. This leads to a behavior where if I select a word with the mouse and the I press backspace key, then I repeat the same step for another word, when I press ctrl+z, the last word removed is returned right after I press ctrl+z, but if I press ctrl+z again the other word removed doesn't return. It occurs because the next action will be the word selection, then the next action will be the mouse click and, finally after I press 3 times the ctrl+z, the other word returns. I don't know if this is the expected result, but my opinion is this behavior is weird.

In order to compare, I did the same steps here in this comment section and the two words that I selected and removed were returned after I pressed ctrl+z twice.

**Comment by Cognitive-dissonance** [comment] 2020-11-18 22:20
Im a new user and not registered yet. But you said it's same on web. I went web, loaded up the plus editor .. did as you said 1 enter, 2 enter, selec and change 1, then 2, hit enter at the end.. ctrl-z undid 2, again, and it undid 1... Ok.. I tried again on the web.. refreshed the page a bunch of times putting my cursor at the top left... but then I finally did as you said except went 1,2,3,4,5,6,7 and randomly changed them to the letter (and enter after each one) this time, I hit ctrl-z twice, possibly 3 , but don't think so.. even if it was 3 though.. all my numbers were back. Retried just in case, and after it undid a couple of them, next ctrl-z did all the rest at once.

**Comment by JaspalSuri** [comment] 2020-11-19 20:41
Hi @Cognitive-dissonance,

Thank you for taking the time to attempt to reproduce the issue! We really appreciate it.

>Hope the app (linux) isn't as flakey..

For what it's worth, the Desktop app is derived from the Web app. 🙂 

You should be able to either reload the web app or reinstall the Minimal Markdown Editor by clicking on the **Extensions** menu on the bottom left half of the screen.

**Comment by effieeee** [comment] 2022-10-29 14:28
No longer occurs on latest apps!

**Closed by effieeee** 2022-10-29 14:28 UTC
