### ISSUE TITLE
Make the checkboxes clickable in preview for the Markdown Pro editor

### ISSUE THREAD

**Issue by ajr0d** [standardnotes/forum#1327] opened 2021-05-16 17:06 UTC
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
Yes.

**Is your feature request related to a problem? Please describe.**
A slight frustration, but when I preview a markdown file (in the Markdown Pro editor) I find myself out of habit trying to click the box to check it. I have to instead Toggle Preview, add an "x" to the box and then flip back.  This occurs on both desktop and iOS

**Describe the solution you'd like**
Just the ability to tap or click the box in preview mode and then it checks itself.

**Describe alternatives you've considered**
I have used other markdown editors and they have the same issue.

**Additional context**
N/A

**Comment by SebTota** [comment] 2021-05-16 22:32
Possible duplicate of #748?

**Comment by JaspalSuri** [comment] 2021-05-19 09:13
Thanks for the feedback @ajr0d and thank you for pointing that out @SebTota. 🙂 Since we cannot implement this feature at the moment I am going to close this thread.

**Closed by JaspalSuri** 2021-05-19 09:13 UTC
Labels: duplicate
