### ISSUE TITLE
Filesafe query

### ISSUE THREAD

**Issue by desfib** [standardnotes/forum#322] opened 2018-09-24 16:55 UTC
Apologies if this is elsewhere 

I have extended and want to use it to protect client files. With Filesafe the files are not stored on my GDrive with the StandardNotes as they are in a different folder (one called Standard Notes and one called Filesafe). 

As these are client files I would prefer to be able to store them together and perhaps move them as I will not always use GDrive (perhaps)

Would I be best to have a zip of one clients files and use filestore for that instead?

Or can we get them to all store together or with the same prefix (title of note)? If title of note I can use my own client number to obfusticate these?

**Comment by mobitar** [comment] 2018-09-25 13:56
Hey @desfib, so are you saying you'd like to be able to specify which folder to save a file in when uploading? That isn't currently supported, but it's an interesting idea.

As for workarounds, you can try prefixing the file with the ID of the client, like 01_doc.pdf, 01_doc2.pdf, etc, where you would keep a reference of what 01, 02, 03, etc map to.

Keeping a zip per client might at some point exceed the 50mb per file upload limit.

**Comment by desfib** [comment] 2018-09-25 21:47
Yes - I had assumed that the uploaded files would be attaching themselves to the Note that was open when I uploaded - dude to the interface being in the same page.

However I now think that it is just a storage vault therefore if I had 50 files would they all show at the bottom of all the notes - in which case this is going to get confusing quickly. 

Could they be included into the folder system somehow?

I realise this is all thoughts - I am just suggesting as I need to get a secure system and would prefer not to purchase yet another online cloud as I have so many. Your input and roadmap is appreciated.

**Comment by mobitar** [comment] 2018-09-26 13:57
Files should be per note, in terms of how they appear inside Standard Notes. So if you attach a file to one note, and navigate to a different note, you shouldn't see that same file. If you are seeing this, then please let me know, as this is unintended behavior which I don't see on my end.

But as for how it looks in your drive, yes, they would all appear in the same folder without distinction per note. We could separate them in your drive by automatically putting them in folders where the folder is the note's ID (or UUID), but that would be a long random string, so not sure how that would help in terms of organization.

**Comment by desfib** [comment] 2018-09-26 22:03
OK thank you - I have my head around it a bit better now - a refresh and it is all showing as you suggest. I think no rush - I will work with it as is a bit - It all might work out OK. I think if I name the files before upload with a client ID prefix then it all might work out OK for searching etc. 

Then it only becomes if I decide to move them - I assume I would then be stuffed - does the offline download only work on a PC etc - I mainly use a chromebook

**Comment by mobitar** [comment] 2018-09-27 14:34
It's all based on web technology, so everything we have should work in the browser.

**Comment by desfib** [comment] 2018-09-28 21:37
So a little experimenting and my chrome browser was not showing the files attahced to note even though they are still in filestore on gdrive. So I checked the android app - no files. So I checked the duck duck go mobile and the files show, however they do not even show in that if I am on a VPN?

- so
Does this mean that I can only access them if I use the same browser? 
Perhaps even the same IP?
This may become an issue if I wipe a computer or routinely move to another browser?
And using a VPN for privacy is routine these days (surely privacy is what standard notes is about)

**Comment by desfib** [comment] 2018-11-26 23:06
Still not able to see my notes - I want to start using this app again however I need this filesafe issue resolved 
It is black Friday and Cyber Monday so I went to look again and still do not see the files?

**Comment by mobitar** [comment] 2018-11-27 15:53
Sorry, must have missed your previous comment. You should definitely see notes regardless of browser/IP. There must be something else going on here. Are you able to open the developer console and see if there are any errors logged when this issue happens? The shortcut is ctrl + alt + i, or something similar. On desktop you can access it via Help -> Toggle Error Console.

**Comment by desfib** [comment] 2018-12-04 15:51
Hi sorry this is about the files attached to the note. 
I want to have client notes and attach docs to the notes however I cannot see the files in different systems or even in the original browser I uploaded them on.

In Google Drive there is a Standard Notes folder and FileSafe folder which has the .json files as I uploaded them however I cannot see these files in standard notes app when that note is open.

In the SN app the FileSafe open at the bottom I just see the attach file button etc 

No encryption keys loaded. Press Expand to generate new keys.
No cloud integrations configured. Press Expand to set up.
?

**Comment by mobitar** [comment] 2018-12-05 17:10
Yeah, that's what we want. But not seeing any errors here. Can you try uninstalling FileSafe and re-installing? Make sure you see some prompts during install about it accessing permissions for metadata related items.

**Comment by desfib** [comment] 2018-12-08 21:59
reinstalled and the files show up, however they cannot be downloaded? 

- but not showing up on the android app - do they work on that or is it only the web version?

**Comment by mobitar** [comment] 2018-12-09 16:37
@desfib what do you mean by they cannot be downloaded? Do you get an error? FileSafe isn't currently supported on mobile. Will be in the future, but we have to sort out these issues first.

**Comment by mobitar** [comment] 2018-12-10 16:18
Hmm, very interesting. Looks to be server error. I'll need to be monitoring the server when this issue happens, so I can know the exact cause. Can you email me at mo@standardnotes.org, so we can coordinate a time when you're hitting the download button so I can take a look at any exceptions server-side?

**Comment by effieeee** [comment] 2022-10-03 16:01
Closing since FileSafe was deprecated

**Closed by effieeee** 2022-10-03 16:01 UTC
