### ISSUE TITLE
Android App Crashes on first Sync after Sign in

### ISSUE THREAD

**Issue by lnolan5017** [standardnotes/forum#1293] opened 2021-04-07 15:40 UTC
**Describe the bug**
Android App crashes on clean installation during initial synchronization.

**To Reproduce**
1. Install Android app
2. Launch Android app
3. During Synchronization, app crashes.
4. I sent an error report on Monday, April 5 after the crash.

**Expected behavior**
Synchronization should complete successfully.

**Tablet (please complete the following information):**
 - Device: Samsung Galaxy Tab S2, 3G RAM, 32G internal storage
 - OS: Android 7
 
**Additional context**
It often takes me several install/reinstalls to get the database synched but this time I can't get it to work at all. I sent an error report in on April 5th. It crashed almost as soon as it started the sync.

Related: https://github.com/standardnotes/forum/issues/1221#issuecomment-807067025

**Comment by mobitar** [comment] 2021-04-07 16:08
Do you have a lot of notes in your account, or perhaps few notes but large in size?

**Comment by lnolan5017** [comment] 2021-04-07 17:23
I have 1363 notes and the largest one is 85Kb when exported as plain text
files.

77 tags.

**Comment by WillRieske** [comment] 2021-08-14 20:37
This is currently a blocker for my daily usage of the service, since the web app is not mobile-friendly.

**Comment by JaspalSuri** [comment] 2021-08-18 07:58
Sorry to hear that, @WillRieske; we'd like to find a way to reliably reproduce this bug so that way we can fix it. Can you provide some additional details as to when you notice the crash occurring (if different from what's shared above)? Do you have any particularly large notes on your account as well?

**Comment by myreli** [comment] 2023-02-13 17:05
Closing as it has the same resolution of https://github.com/standardnotes/forum/discussions/2474#discussioncomment-4960745

**Closed by myreli** 2023-02-13 17:05 UTC
Labels: bug
