### ISSUE TITLE
Conflicted copy--completely unusable

### ISSUE THREAD

**Issue by eambutu** [standardnotes/forum#928] opened 2020-04-09 04:13 UTC
I'm getting this error when I try to edit my notes on any platform--desktop app, webapp, on mac, on PC. Everytime I try to edit a note, it creates a separate copy that says, "conflicted copy" and I have to go and manually delete all these new notes. I've been having this issue for maybe a month? And my internet is fine. 

I hope there is a workaround or a fix, because I like the idea of Standard Notes, but this is game-breaking.

![image](https://user-images.githubusercontent.com/11009767/78857290-d36b9d80-79dd-11ea-84c0-ebcf1c07f3db.png)

**Comment by JaspalSuri** [comment] 2020-04-09 05:50
Hi, we've had something similar reported to us but the issue (according to what I know) simply disappeared for the user and no one was able to reproduce it. 

Have you tried logging out of all the clients, making sure that you're on the latest version the desktop apps, and then logging back in again?

**Comment by mobitar** [comment] 2020-04-09 14:46
The "unnecessary duplication" issue, although very rare, has been impossible for us to replicate. However, the good news is that as part of the 3.5 release, the syncing and conflict architecture will be greatly, greatly improved, to the point where this should not be an issue anymore. The ETA for 3.5 is anywhere from 2-4 months.

**Comment by eambutu** [comment] 2020-04-26 00:01
Is there any short term fix? This is happening consistently, basically everytime I go back to write a note. I don't want to make this huge effort of exporting all my notes, especially after I paid for a year for this thing.

**Comment by eambutu** [comment] 2020-04-26 00:24
Alternatively, can I go retrieve any logs that would be helpful for you all? Or give you account info that would help diagnose the problem?

**Comment by JaspalSuri** [comment] 2020-05-01 10:09
Hi Phillip,

Have you tried logging out of all of your devices and logging back in? Out of precaution, it would be recommended to back up everything just in case, but you shouldn't lose any data.

While logs might not help us since we haven't been able to reproduce the issue, you can share them by opening the desktop and/or web app, pressing <KBD>Command/Control + Shift + I</KBD> (for macOS and Windows, respectively), making a new note, and copying whatever appears in the console tab and then share them here or email help@standardnotes.org for a more private option.

**Comment by mobitar** [comment] 2020-05-01 14:44
Version 3.5, which is under active development, but does not have a definite release date just yet, will address this issue.

**Comment by TheodoreChu** [comment] 2021-01-12 06:54
Version 3.5 was released months ago and conflicted copies at this quantity doesn't seem to happen anymore, so I'm closing this issue. Feel free to comment or open a new issue if you have more issues

**Closed by TheodoreChu** 2021-01-12 06:54 UTC

**Comment by dddvision** [comment] 2021-11-03 22:10
This issue is occurring today on macos version 3.8.21. It is a severe problem, and it is the only reason why I did not sign up for a 5-year subscription today.

**Comment by HaithamMaya** [comment] 2021-11-04 01:29
I am on 3.8.21 on linux and I am also getting the conflicted copy error
