### ISSUE TITLE
[Help Wanted] only Message Window showing

### ISSUE THREAD

**Issue by adr41n** [standardnotes/forum#1399] opened 2021-08-19 18:02 UTC
I can only see the note window, so can't select another note.
There are no grabable or movable borders visible.

See attached screenshot ( Blank lines inserted to hide private Info )
![Screenshot (2)](https://user-images.githubusercontent.com/7623640/130120175-0f6369b4-ca80-445d-8e00-5e56080cbe76.png)

Note Also multiple Action Bars" at bottom of page

Problem the same in both Windows and Ubuntu (Snap) App also Web page under Firefox and Chrome.

**Comment by mobitar** [comment] 2021-08-20 14:14
If you hover over the left side of the window, your cursor will turn into a resizer icon and you can drag out to expand the collapsed notes and tags list.

**Comment by adr41n** [comment] 2021-08-22 03:24
Hi, Thx for replying, btw it's the Advanced Markdown Eitor, If I hover to the right of the note, I get a resizer icon, if I drag it to the right I get a white space, but still no access to collapsed notes or tags.
![Screenshot (5)](https://user-images.githubusercontent.com/7623640/130340824-0bef39f4-bb5c-4029-83cc-31ce9c569837.png)

If I hover closer to the LHS only when I get close to the Window edge does anything happen and I get the Window resizer.

**Comment by JaspalSuri** [comment] 2021-08-24 06:21
Sorry to hear that. It looks like Margin Resizers is enabled. Even in that state, if you were to keep dragging from the LHS, does it only adjust the size of the overall window instead of the the width of the notes list and tags pane? Did this issue occur before upgrading to Windows 11? Which version of the app is running, according to the bottom of what's list in the **Account** menu? Can you reproduce this issue with the [web app](https://app.standardnotes.org)?

**Comment by adr41n** [comment] 2021-08-24 09:50
I am primarily running Linux, ( Ubuntu ) but the same problem exists in Windows 10/11 and the Web app.
I reported it in Win 11 only because I was setting up the machine and needed to stay in that environment for a while, I also hoped the problem would not be seen in Windows, but no, exactly the same as in Ubuntu ( Virtually unusable ).

Dragging from the LHS only adjusts the width of the Window

**Comment by adr41n** [comment] 2021-08-30 03:13
Hi, it's a Holiday weekend here, I am away from my machine, I will try your suggestion when I return home on Tuesday.

**Comment by JaspalSuri** [comment] 2021-08-31 06:46
Thank you for letting us know. 🙂 We hope you'll be able to enjoy your Holiday weekend!

**Comment by adr41n** [comment] 2021-09-01 23:06
Hi, I cleaned up all the extensions so there was only one of each and removed the themes as you suggested.
It took a while but things seem better now, at first no change but after maximizing the window and then restoring again all the panes are visible again.
Thanks for your help with this

**Comment by JaspalSuri** [comment] 2021-09-02 07:27
You're very welcome; I'm glad to hear that! Thank you for taking the time to try that and for letting us know that the panes are visible again. 🙂

**Comment by myreli** [comment] 2023-02-21 18:18
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed by myreli** 2023-02-21 18:18 UTC
Labels: help wanted
