### ISSUE TITLE
search for inexistent text creates note

### ISSUE THREAD

**Issue by hillbilly3456avk** [standardnotes/forum#1307] opened 2021-04-28 05:34 UTC
**Describe the bug**
When i type a search text that does not exist in any of my notes, it will eventually create a note with the searchtext as title

**To Reproduce**
1. Open Standardnotes
2. **EDIT** Click on "Views->AllNotes"
2. Type a text that does not exist in your notes into the searchbar
3. wait and do nothing
4. after a few seconds a new note with the searchtext as title is created

**Expected behavior**
If the text in the searchfield does not exist within the notes, the search result should stay empty. Nothing else should happen

**Screenshots**
not applicaple

**Desktop (please complete the following information):**
 - Windows, Linux
 - StNo Version 3.6.8

**Smartphone (please complete the following information):**
not duplicatable on iOS

**Additional context**
**EDIT** Seems to be somehow hard to duplicate. Happens consistently when i have a searchtext in the field and switch views
**EDIT** Passcode lock is active
I have installed the folders extensions. It seems, that this issue only happens when I am in the top folder.

**Comment by JaspalSuri** [comment] 2021-04-28 09:24
Hi @hillbilly3456avk, thank you for bringing this issue to our attention. I'm afraid that I haven't been able to reproduce it yet. Are you using a passcode lock on the app? Does this issue happen consistently, or only after you launch or unlock the app?

**Comment by mobitar** [comment] 2021-04-28 12:55
There is a feature where if you press + with some text in the search bar, it will create a note from it. What seems to be happening here is some mangling of this feature where when the 30s sync timer hits, it creates a placeholder note for some reason.

**Comment by antsgar** [comment] 2021-06-24 18:23
Closing as this is now fixed on version 3.8.10 🙂

**Closed by antsgar** 2021-06-24 18:23 UTC
Labels: bug
