### ISSUE TITLE
[Feature Request] Collaboration

### ISSUE THREAD

**Issue by tsunamitreats** [standardnotes/forum#286] opened 2018-08-28 13:44 UTC
Users would be able to add email addresses of other Standard Note users on a note-by-note basis to enable sharing of these notes.

**Comment by mobitar** [comment] 2018-08-29 14:17
Encryption makes this tricky. There aren't many solutions for client-side collaboration; most of them are server-side, where the server needs to be able to read the note contents. So, we're holding off on this until client-side collaboration matures a little more.

**Comment by TheodoreChu** [comment] 2021-01-11 03:59
Closing this because it's a duplicate of https://github.com/standardnotes/forum/issues/52

**Closed by TheodoreChu** 2021-01-11 03:59 UTC
Labels: duplicate, enhancement
