### ISSUE TITLE
Laggy Version 3.9.15

### ISSUE THREAD

**Issue by snakespan** [standardnotes/forum#1512] opened 2022-01-14 14:41 UTC
**Describe the bug**
New version of standard notes when using with the Plus Editor in Windows is laggy. I have a big itemised list (around 3000 items) and since the update, I'm now waiting for things I've typed to appear.

**To Reproduce**
1. Open Standard Notes version 3.9.15 in Windows
2. Start a list with the Plus Editor (it might require a long list)
3. Observe that typing is laggy 

**Expected behavior**
Expect not to wait for characters to appear when typing, while Standard notes computes.

**Screenshots**

**Desktop (please complete the following information):**
Windows, App, 3.9.15

**Additional context**

**Comment by stefan-yas** [comment] 2022-01-17 08:14
Hey @snakespan, thanks for the report! I could reproduce your issue, although I needed a bigger dataset (around 10k items) to notice the lagginess. We've had increased reports of the issue with editors being laggy, when dealing with large notes since a couple of versions ago, when we bumped our Electron version, which the app is based on. We think the issue is with Electron itself and are continuing to monitor Electron releases so we can implement a fix when it's ready.

**Comment by moughxyz** [comment] 2022-01-17 13:17
This should be fixed in an upcoming release where you'll have the ability to toggle spellcheck off per-note with support for Plus, Bold, and Markdown Pro editors. Disabling spellcheck in these editors vastly improves performance.

**Comment by snakespan** [comment] 2022-01-17 13:30
Thanks, yes my dataset is around 3000 items. What seems to help is switching from one note to another and performance slightly improves for about a minute, but then becomes unbearable, hopefully due to the spell checker which I absolutely don't need in this particular note.

**Comment by snakespan** [comment] 2022-01-25 10:22
You can consider this item closed now as per the latest update. I am experiencing no more lagginess on Windows.

**Closed** 2022-01-25 10:44 UTC
Labels: bug
