### ISSUE TITLE
Search for text within a note: Feature missing in OSX

### ISSUE THREAD

**Issue by DaveFlowberries** [standardnotes/forum#1292] opened 2021-04-07 04:30 UTC
Maybe I am doing something wrong, but I can't find the function.

**Comment by JaspalSuri** [comment] 2021-04-10 04:08
Hi @DaveFlowberries,

Currently the scope of the search feature is limited to searching for text in the titles & bodies of each note. You can also narrow search results to certain notes by selecting a tag before performing a search. The ability to search within a note isn't currently available but is on our long-term roadmap. 🙂

While not optimized for devices that aren't connected to a physical keyboard, there are ways to search for text within a note by using certain editors, such as the Vim-mode in the Code Editor, the Monaco editor within the [Append Editor](https://appendeditor.com), and the Markdown Minimist Editor. You can use the <KBD>CTRL</KBD>/<KBD>CMD</KBD> + <KBD>F</KBD> keyboard shortcut in the latter two editors and <KBD>CTRL</KBD>/<KBD>CMD</KBD> + <KBD>SHIFT</KBD> + <KBD>F</KBD> keyboard shortcut in the Monaco Editor within the Append Editor. 

I am going to close this thread since it is a duplicate of #330, but please let us know if you have any additional questions and/or feedback! 🙂

**Closed by JaspalSuri** 2021-04-10 04:08 UTC
