### ISSUE TITLE
Error decrypting [SOLVED]

### ISSUE THREAD

**Issue by bepolymathe** [standardnotes/forum#16] opened 2017-07-18 08:22 UTC
Hi,

New problem...

![captureerror](https://user-images.githubusercontent.com/29939805/28307285-b26937a6-6ba2-11e7-8109-438ab6dcbd4e.PNG)

I have tried to sign out / sign in but it don't change anything.

**Comment by mobitar** [comment] 2017-07-18 14:24
Please make sure you're running the latest version of all apps you're signed into. Otherwise you'll see this error.

iOS: 1.3
Desktop: 1.2
Android 1.4

**After you upgrade, sign out then sign back in.**

**Comment by mobitar** [comment] 2017-07-18 16:22
I've added a FAQ section here that should help clear things up: https://standardnotes.org/verification

**Comment by bepolymathe** [comment] 2017-07-18 16:58
Same problem for me with the 1.2.0 on linux + repetition of tags 

![screenshot_20170718_185502](https://user-images.githubusercontent.com/29939805/28329665-e29b0dc6-6bea-11e7-8b1f-38bb2176a188.png)

Maybe i can delete all notes in the dashboard ? I have an export from before the importation of txt files...

**Comment by mobitar** [comment] 2017-07-18 17:29
Ya, you can delete all your data from the dashboard. 

Account -> Advanced -> Data Dasboard -> Login -> Data -> Advanced -> Destroy all data

**Comment by bepolymathe** [comment] 2017-07-18 20:00
Ok, it's all right. It work great.

**Comment by carlinmack** [comment] 2020-05-15 23:22
Why aren't issues like this closed?

**Comment by JaspalSuri** [comment] 2020-05-18 00:39
I'm sorry that it wasn't closed. I haven't gone through the old GitHub threads yet to close ones that have been resolved. 

Sometimes an issue is resolved but another user experiences it later. 

Mo was working solo for quite a long time, so he had to prioritize his time accordingly to make sure everything was running smoothly. :) 

I'll go ahead and close it now.

**Closed by JaspalSuri** 2020-05-18 00:39 UTC

**Comment by carlinmack** [comment] 2020-05-18 01:03
As long as the issue is resolved I feel like it should be closed, people who experience it later will find it in search :) 

Lots of the oldest issues, like this, 13 and 4 can be closed in this fashion

**Comment by mobitar** [comment] 2020-05-18 13:28
On the forum we don't really care too much about open/close. Because in many cases the issues will just be open-ended discussions. But I suppose if an issue clearly qualifies to be closed it would make sense.
