### ISSUE TITLE
Not working on iOS 17.1?

### ISSUE THREAD

**Issue by 24hourbreakfast** [standardnotes/forum#3318] opened 2023-10-26 11:07 UTC
**Describe the bug**
When I open the app in iOS 17.1, all I get is a white screen. Nothing changes. Restarting the app didn’t help. Neither did restarting phone. 

Device: iPhone 15 Pro Max
IOS: 17.1

**Comment by effieeee** [comment] 2023-11-01 12:49
Hi @24hourbreakfast, have you also tried reinstalling the app on your device? If you're using the app offline without an account, please also make sure that you [export a backup of your notes](https://standardnotes.com/help/14/how-do-i-create-and-import-backups-of-my-standard-notes-data) before you reinstall the app.

**Comment by fad1** [comment] 2023-12-15 22:40
I had a similar issue caused by lockdown mode enabled for the app.

**Comment by effieeee** [comment] 2023-12-19 14:38
In case this might actually be caused by a lockdown mode limitation as mentioned above, please check if adding Standard Notes as an exception might help:

https://github.com/standardnotes/forum/issues/3051#issuecomment-1658890314

**Comment by LorenzoMusso** [comment] 2024-04-16 23:54
Can confirm that iOS App version 3.193.2 actually is bugged even with the exception active in lockdown mode in iOS 17.4.1 on iPhone 15

**Comment by effieeee** [comment] 2024-04-18 18:51
Hi @lorenzomoon, indeed this is a known issue on iOS 17.4 when Lockdown Mode is active (#3514). I'll be closing this thread, and you may follow #3514 instead 🙏

**Closed as completed by effieeee** 2024-04-18 18:51 UTC
Labels: bug
