### ISSUE TITLE
[Help Wanted] Unable to convert Google Keep to Standard notes

### ISSUE THREAD

**Issue by wulunzun-web** [standardnotes/forum#1216] opened 2021-01-19 11:07 UTC
Hi,

I followed the instructions to export my Google Keep files into Takeout folder then used the Standard Notes convert tool to convert the files. But it keeps giving me an error: "There was an error processing your file. Please submit your console output to help@standardnotes.org."

There are html, json, png and jpg files in the keep folder. I tried selecting all the files, and json + html and both gave me the same error. Then, I selected only json files and it gave me a "keep-to-sn.json" file to download. The file is 17kb. After downloading, I imported it using the "Import Backup" function as instructed but nothing was imported. I opened the json file using a text editor and found that nothing was inside the file. Only 
```
{
  "items": []
}
```
Can someone help me with this?

Edit: I tried converting the files to .enex so that I can use the Evernote conversion. Again, it processed but nothing was shown after unpacking the .enex file. I used Joplin and it was successful.

**Comment by JaspalSuri** [comment] 2021-01-20 01:13
Hi @wulunzun-web,

I'm sorry to hear that; I'm afraid that I wasn't able to reproduce the issue. It could be because I'm not converting as many files. What is the size of the takeout?

Please try importing your notes via the converter tool once more and use the following steps to view the error message:
1. Right-click anywhere on the [tools' page](https://dashboard.standardnotes.org/tools).
2. Click on **Inspect Element** option in the context menu
3. Click on the **Console** tab.

Please send us a screenshot of whatever you see highlighted in red and we'll look into it from there.

**Comment by thetabor** [comment] 2021-01-23 19:28
@wulunzun-web if you need a short term solution, look here:

https://gist.github.com/lzambarda/5e6cebd8356d3a2b5a2de01068745f5b

I was getting the same error, already submitted my console output to the help email. But, I was impatient to get it done.

**Comment by myreli** [comment] 2023-02-21 15:28
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed by myreli** 2023-02-21 15:28 UTC
Labels: help wanted
