### ISSUE TITLE
Failed Daily Backup to OneDrive CloudLink

### ISSUE THREAD

**Issue by infosisio** [standardnotes/forum#1286] opened 2021-04-01 11:24 UTC
Describe the bug:
My Daily Backup to OneDrive is not working. I received an email with the subject "Failed Daily Backup to OneDrive Sync".

To reproduce:
I've tried uninstalling and reinstalling but when I click "Perform Backup" it fails and I get another email.

Expected behaviour:
Backup should work.

Desktop (please complete the following information):
OS: Ubuntu 20
Standard Notes version: 3.6.4 (Snap)

**Comment by JaspalSuri** [comment] 2021-04-02 23:50
Hi @infosisio, I apologize for not getting back to you on this sooner. Thank you for taking the time to create a report and for providing those details.

We're aware of this issue and a member of the team created an issue on Microsoft's OneDrive API Docs repo here: OneDrive/onedrive-api-docs#1463

I'm going to close this thread since it is a duplicate of thread #1271.

**Closed by JaspalSuri** 2021-04-02 23:50 UTC
Labels: bug

**Comment by AryanM26** [comment] 2022-11-07 12:07
Is it a secure way to migrate OneDrive files using third-party software? As I was going through this article that explains the manual and software approach to [migrate data from OneDrive to OneDrive](https://www.migrateclouddata.com/blog/migrate-data-from-onedrive-to-onedrive/). So, I am confused and want to know if this approach is secure or not.
