### ISSUE TITLE
Listed private links not working

### ISSUE THREAD

**Issue by aaantoszek** [standardnotes/forum#692] opened 2019-09-15 13:28 UTC
All Listed private links redirect to the main blog

Tried on 3 different blogs

**Comment by mobitar** [comment] 2019-09-16 14:32
I can't reproduce this. Are these posts that are newly privately published, or previously privately published? Can you provide sample links?

**Comment by aaantoszek** [comment] 2019-09-16 14:59
Try this: https://blog.antoszek.eu/p/Kry9GOZXZM

Redirects to main blog in Brave & Edge

**Comment by aaantoszek** [comment] 2019-09-16 15:00
Happens to all private posts. No matter how old.

**Comment by bryvin** [comment] 2019-09-16 15:23
What's interesting here is that it seems to work when you remove /p/ from the URL. For example: [https://blog.antoszek.eu/Kry9GOZXZM](https://blog.antoszek.eu/Kry9GOZXZM)

@mobitar Maybe this has something to do with your recent commit to move private posts to /p ?

**Comment by mobitar** [comment] 2019-09-16 15:23
It looks to be a custom domain issue. Investigating..

**Comment by mobitar** [comment] 2019-09-16 15:29
Should be fixed now.

**Comment by aaantoszek** [comment] 2019-09-16 15:29
@mobitar Works! Thanks

**Closed** 2020-05-11 19:52 UTC
