### ISSUE TITLE
Search function is sensitive to accents 

### ISSUE THREAD

**Issue by machocam** [standardnotes/forum#336] opened 2018-10-08 14:37 UTC
Your search function is sensitive to accents. i.e for you "e" not equal to "é" which is dangerous. 
A user might forget to type the accent and miss out on that input in her search results. 
Most large apps (windows, OSX and many others) make both of these equal in terms of search because of that.

**Comment by mobitar** [comment] 2018-10-08 14:47
Thanks, I can confirm this behavior. Will need to investigate.

**Comment by TheodoreChu** [comment] 2021-01-12 07:05
Duplicate of https://github.com/standardnotes/forum/issues/304

Closing this issue because it is fixed on the latest desktop apps (v3.5+): https://standardnotes.org/download

**Closed by TheodoreChu** 2021-01-12 07:05 UTC
Labels: duplicate
