### ISSUE TITLE
Duplicate Notes

### ISSUE THREAD

**Issue by specter78** [standardnotes/forum#1280] opened 2021-03-26 17:08 UTC
I am using SN mostly on the web. For some reason, my notes are getting duplicated with 2, in some cases 4, notes containing the same title and content. This has started to occur recently.

**Comment by mobitar** [comment] 2021-04-01 01:04
Hey @specter78, did this happen for all your notes, or only certain notes as you were editing them?

**Comment by specter78** [comment] 2021-04-01 13:40
All (or most) notes, even those which I didn’t edit.

I do have a mobile app too, but I use it for viewing notes only and not
editing. Not sure whether this would help.

**Comment by atmoio** [comment] 2021-04-02 12:45
We've potentially identified the source of this issue and will issue an update sometime next week 👍

**Comment by MarioCatuogno** [comment] 2021-04-09 12:31
I have had the same problem, but not only my notes got duplicated but also tags (in some cases multiple times).

@mobitar Is the update been deployed yet?

**Comment by mobitar** [comment] 2021-04-09 16:58
Update will be deploying on Monday. It should better handle one-off duplication, and solve the batch duplication issue. Most likely the reproduction steps above are very subjective and related to local environment/network factors (such as using a VPN).

**Comment by MarioCatuogno** [comment] 2021-04-09 17:34
@mobitar  thank you! I will try again with the next update.

**Comment by MarioCatuogno** [comment] 2021-04-13 21:08
I've replicated the steps above and can confirm that with version 3.6.6 the issue is not present anymore.

Thanks!

**Comment by myreli** [comment] 2023-02-21 15:46
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed by myreli** 2023-02-21 15:46 UTC
