### ISSUE TITLE
Todo editor layout, font, interaction are all messed up in Firefox

### ISSUE THREAD

**Issue by cormacrelf** [standardnotes/forum#194] opened 2018-04-04 15:48 UTC
![screen shot 2018-04-05 at 1 37 42 am](https://user-images.githubusercontent.com/378760/38318149-0d35fc18-3872-11e8-92dc-a1746b45a513.png)

Issues, which AFAICT all only occur in Firefox:

- Monospace, obviously. Should be sans.
- Misaligned checkboxes
- Clicking on text won't move the cursor, you have to use the arrow keys to get around
- Sometimes clicking on a todo won't activate it at all
- Sometimes bottom of a long todo will get chopped off, especially if resizing

Firefox treats { having `Content-Security-Policy: ...; script-src 'self';`, but using 'eval' in a script (compiled.min.js) } as an error and reports it in the console. That's the only thing that seems to be actually different in FF, at least to me. Plus it's an issue anyway.

I use Firefox stable on a Mac. Can't use Chrome or indeed the Chrome-based (?) desktop builds because they hate my Nvidia GPU and refuse to use it for scrolling.

**Comment by mobitar** [comment] 2018-04-05 15:53
Hmm...can indeed replicate some of these issues. The clicking issues are caused by the Sortable library we use to allow for re-dragging. Not sure what chance there is of fixing that I'm afraid. Will need to find some workaround. I've made a note of this and hope to allocate some time to it soon.

**Comment by TheodoreChu** [comment] 2021-01-11 03:43
Closing this because the issues described don't seem to affect the latest version of the editor

**Closed by TheodoreChu** 2021-01-11 03:43 UTC
