### ISSUE TITLE
Linking notes

### ISSUE THREAD

**Issue by bitic** [standardnotes/forum#293] opened 2018-09-06 08:53 UTC
I'm an Evernote user considering to migrate to standard notes.

An Evernote feature I use a lot is linking notes. Is there a way to link notes in standard notes?

**Comment by mobitar** [comment] 2018-09-06 13:08
There's no way to presently link notes. However, this is definitely on our radar. Still no dates, but likely a long term priority.

**Comment by bitic** [comment] 2018-09-06 13:27
Thanks for the answer.

For me, links, attachments and reminders are necessary before being able to
transition from Evernote.

**Comment by TheodoreChu** [comment] 2021-01-12 06:25
Closing this because it is a duplicate of https://github.com/standardnotes/forum/issues/324, which has a longer conversation

**Closed by TheodoreChu** 2021-01-12 06:25 UTC
Labels: duplicate, enhancement
