### ISSUE TITLE
Android app keeps crashinb

### ISSUE THREAD

**Issue by dh99taf** [standardnotes/forum#1378] opened 2021-07-22 23:52 UTC
Just downloaded ver 3.6.21 via F-Droid on an Android version 8 Samsung Galaxy S7 phone. The app won't even open. Every time I try to open it, it crashes and says that the app has stopped.

**Comment by JaspalSuri** [comment] 2021-07-25 18:54
Hi @dh99taf, I'm going to close this thread since it's a duplicate of https://github.com/standardnotes/forum/issues/1378.

**Closed by JaspalSuri** 2021-07-25 18:54 UTC
Labels: duplicate
