### ISSUE TITLE
[Help Wanted] All notes / tag categories duplicated

### ISSUE THREAD

**Issue by dsclough** [standardnotes/forum#1177] opened 2020-12-26 15:59 UTC
Hi,

Recently all of my notes have been duplicated. Is there any way to easily fix this without manually going through and deleting all the duplicates? I'm using the latest version of the mobile app and the web interface as the only two places I'm syncing notes from. I had about 1500 notes, now 3000, so manually deleting the 1500 duplicated notes doesn't seem like a reasonable fix.

**Comment by mobitar** [comment] 2020-12-28 16:50
Strange. Any idea what caused the event? Did you perform any special action, or see any unexpected behavior?

For now you should be able to use the Batch Manager extension to detect and delete duplicates.

**Comment by iknowanon** [comment] 2021-01-18 07:18
Just had this happen as well. Mac Desktop, was asked to re-enter password, all the notes were showing as encrypted. Once decrypted, notes and tags were all duplicated. Tried to delete app and re-install, but the phenomenon was already passed on to other devices. 

I notice a 'tell' for the dupes: they have all reverted to the standard editor, so all their markdown code is showing.

**Comment by mobitar** [comment] 2021-01-21 16:47
At this point we can be sure that this issue does indeed exist, as I've heard it from a few people. But still no leads as to what can cause this. If you notice this again, please try to jot down the steps you took preceding this that caused it to happen.

**Comment by yingw787** [comment] 2021-01-28 06:05
I've had this happen too; is there an easy way in order to transform the backup we get (maybe compare encrypted hashes) and filter out duplicates, then restore from backup that way?

**Comment by iknowanon** [comment] 2021-01-28 07:01
Here's what I did, iirc:
First, for any notes where I used a non-default editor, they had reverted
back to it, and all their markdown code was now showing. Next all my tags
had been duplicated. For each tag, I looked at which of the two versions
contained these files that showed the markdown code. It was one *or* the
other of the two with the same tag. I renamed the faulty one. e.g. I had
two groups with the same tag name "Example" the one with the faulty files,
aka the duplicate, I renamed "Example faulty."  Then I activated the batch
manager, and did a batch delete of the files with tag "Example Faulty."
This was faster than going through files manually, since I have a lot of
notes.

Second, having cleared out those files, I did a regular "find duplicate
files" in the batch manager.  I noticed that the duplicated files were all
from the same date and time, which was "today". In my case they were always
the second file of each pair. So I just ticked all those and did another
batch delete.

**Comment by schutzekatze** [comment] 2021-03-18 02:25
This (or somewhat similiar) issue just happened to me. The difference is that for me, not all notes were duplicated, only a subset of them. I think I know what happened, though, so I'll try to explain.

I'm only using web interface, so it shouldn't be an issue of syncing between devices. I noticed today when I was editing a note that it says "Offline" in the bottom right corner of the interface and that when I click the "Account" button on bottom left of the interface, it's giving me the option to login. This was surprising to me, as I could see all my notes despite not being logged in? Perhaps they were cached or something similar. Right after I logged in, a number of notes got duplicated and I noticed that it was only those that I recently changed (in the past couple of days). I could see that when I compared the duplicated note pairs that the older versions didn't contain recent changes. I'm guessing is that the notes that got duplicated are the ones that I was editing between the time I was logged in days ago till today, when I was (somehow?) working in offline mode and so with (cached?) notes.

Cheers, hope this helps.

**Comment by mobitar** [comment] 2021-03-18 12:31
Interesting. Are you using Firefox? Sometimes if you clear your browsing data, or have it set to autoclear, it will clear your localStorage (where your account details are stored), but not your IndexedDB (where your notes are stored).

**Comment by schutzekatze** [comment] 2021-03-18 18:48
I am using Firefox and I have indeed cleared browsing data recently, including cache.

**Comment by JaspalSuri** [comment] 2021-03-19 17:41
Hi @schutzekatze,

Thank you for providing those details. 🙂 

Can you walk us through what you did after clearing your browsing data? Did you reload the web app's tab or restart Firefox at any point until you noticed that you were signed out? 

Did you clear the browsing data, leave your computer, and return to it later? Did you see a prompt saying **Authentication Required**?

When I tried reproducing the issue, the web app provided an error alert for each character that I inserted into a note, and it appeared as though I was still signed in, preventing me from signing in again. Did you make changes to your notes or create new notes afterwards? 

Also, were you using a pinned tab?

**Comment by schutzekatze** [comment] 2021-03-20 00:36
As far as I remember, it was days difference between clearing browing data and seeing the duplication issue, with many computer shut downs and browser restarts in that time. When the issue happened, I don't remember seeing "Authentication required". I only got the login menu if I clicked the "Account" button on the bottom left of the interface. Also, I was not using pinned tab.

I tried reproducing the issue now but wasn't successful. I'll let you know if I manage to do it.

**Comment by schutzekatze** [comment] 2021-03-20 00:41
I guess I should add -- I've been using standard notes for a while now and this was the first time this happened. I am pretty sure I've been clearing my browser data plenty of times before and relogging into standard notes without issues so this might not be easily reproducible. Fortunately, thanks to Batch Manager it's not too much of an issue either.

**Comment by JaspalSuri** [comment] 2021-03-20 18:21
> Fortunately, thanks to Batch Manager it's not too much of an issue either.
We're glad to hear that! Thank you so much for providing all of those details. 🙂 

What operating system were you running Firefox on?

**Comment by schutzekatze** [comment] 2021-03-20 20:50
Linux. I also have Privacy Possum, Privacy Badger, and AdNauseam extensions which may have interfered with the page?

**Comment by JaspalSuri** [comment] 2021-04-11 01:02
Hi @schutzekatze, I apologize for the delayed response; thank you for sharing that. It appears that the issue currently isn't related to the add-ons that are being used. The next version of the web app will contain a fix for this issue and we plan to release it on Monday. 🙂

**Comment by myreli** [comment] 2023-02-15 14:51
Seems like this issue was solved and is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Closed by myreli** 2023-02-15 14:51 UTC
Labels: help wanted
