### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by astingengo** [standardnotes/forum#1302] opened 2021-04-19 18:19 UTC
**Describe the issue**
I have self hosted standard notes and having 413 issue
The title errors appears on logs on api-gateway
On console [inside the dekstop app] I'm having 413 payload too large error and 
```
app.js:2 SyntaxError: Unexpected token < in JSON at position 0
```
I added 
```
client_max_body_size 100M;
client_body_buffer_size 100M;
client_header_buffer_size 100k;
large_client_header_buffers 2 100k
```
to nginx config but this is not helping.
I'm using Docker for everything [nginx as well]

**To Reproduce**
Restore my backup notes

**Expected behavior**
Be able to sync notes on the server.
I created another account and I was able to sync only one note.
The problem seems to be when I'm trying to sync all my backup notes

**Desktop (please complete the following information):**
Ubuntu 20.04 Desktop app version 3.6.7

**Comment by mobitar** [comment] 2021-04-19 19:14
cc @karolsojko is there a fix that works while users await official fix?

**Comment by karolsojko** [comment] 2021-04-20 03:32
@mobitar none yet. This is on my short-list.

closing this one as duplicate of: https://github.com/standardnotes/forum/issues/1281

**Closed by karolsojko** 2021-04-20 03:32 UTC
Labels: help wanted
