### ISSUE TITLE
FileSafe-relay not working on Synology NAS

### ISSUE THREAD

**Issue by BobWs** [standardnotes/forum#1083] opened 2020-08-29 10:34 UTC
Hi,
Would you please share a step-by-step how you configure your Synology NAS to work with FileSafe-Relay?

I keep getting a error that the file couldn't be uploaded.

>Now everything works for me. Thanks for helping me solve my problems.
>BTW where can I find out about ROADMAP for 2019?
>
>_Originally posted by @konklon in https://github.com/standardnotes/forum/issues/407#issuecomment-451674276_

**Comment by JaspalSuri** [comment] 2020-09-01 09:17
I'm not sure if we can provide a guide yet on how to set it up, but maybe we can help by resolving some issues that coincidentally make things work in your case. Can you give us some more details about your current set up and provide any logs that have been outputted?

**Comment by BobWs** [comment] 2020-09-01 12:52
> I'm not sure if we can provide a guide yet on how to set it up, but maybe we can help by resolving some issues that coincidentally make things work in your case. Can you give us some more details about your current set up and provide any logs that have been outputted?

Hi, Thanks for replying.

This is how I setup the relay server on Docker Synology
```
docker pull standardnotes/filesafe-relay:stable
docker run -d \
 -p 3004:3000 \
 --name standardnotes-filesafe-relay\
 --hostname='standardnotes-filesafe-relay' \
 -e TZ='My/Timezone'\
 -v /etc/localtime:/etc/localtime:ro \
 -v /etc/TZ:/etc/timezone:ro \
 -e SECRET_KEY_BASE='use "secret-key"'\
 -e HOST='http://192.168.178.115:3004'\
 -e RAILS_ENV='production'\
 -e RAILS_LOG_TO_STDOUT='false'\
 -e DATADOG_ENABLED='false'\
 --restart='always' standardnotes/filesafe-relay:stable
```

When trying to login to a webdav-server I see this when I enter this in my browser
`http://192.168.178.115:3004`


![screen_1](https://user-images.githubusercontent.com/5485820/91853231-2fbbac00-ec62-11ea-8d88-b3f4eaabd698.png)

![Screen_2](https://user-images.githubusercontent.com/5485820/91853292-45c96c80-ec62-11ea-8da8-887eb23e600f.png)

![Screen_3](https://user-images.githubusercontent.com/5485820/91853353-5b3e9680-ec62-11ea-9184-442942cd2f08.png)

![Screen_4](https://user-images.githubusercontent.com/5485820/91853376-6265a480-ec62-11ea-988e-6079cf039303.png)

After this when trying to upload a file/picture I get an error that the file couldn't be uploaded.
I can't find anything in the log file

**Comment by mobitar** [comment] 2020-09-01 13:33
Who is the WebDAV host in this case? What is the endpoint you are using when configuring it? And is SN running locally on the same machine as the relay server (it would have to with your configuration)?

**Comment by BobWs** [comment] 2020-09-01 13:47
> Who is the WebDAV host in this case? What is the endpoint you are using when configuring it? And is SN running locally on the same machine as the relay server (it would have to with your configuration)?

Thanks for your reply.
I just figured it out. Everything is working now! 
I have manage to connect and upload to my pCloud account via FileSafe-Relay/Webdav and uploaded a test file.

**Comment by mobitar** [comment] 2020-09-01 13:48
What was the issue :)

**Comment by BobWs** [comment] 2020-09-01 16:03
> What was the issue :)

Well I guess the problem was that the link wasn't going outside my NAS. The moment I used my reverse proxy for the FileSafe intergration link (e.g. https://relay.mydomain.com) it started to work and I could upload to pCloud through Webdav.

Thanks again for reaching out!

**Comment by BobWs** [comment] 2020-09-01 16:13
This is how I setup a working Relay-server on Docker Synology
```
docker pull standardnotes/filesafe-relay:stable
docker run -d \
 -p 3004:3000 \
 --name standardnotes-filesafe-relay\
 --hostname='standardnotes-filesafe-relay' \
 -e TZ='My/Timezone'\
 -v /etc/localtime:/etc/localtime:ro \
 -v /etc/TZ:/etc/timezone:ro \
 -e SECRET_KEY_BASE='use "secret-key"'\
 -e HOST='https://relay.mydomain.com'\
 -e RAILS_ENV='production'\
 -e RAILS_LOG_TO_STDOUT='false'\
 -e DATADOG_ENABLED='false'\
 --restart='always' standardnotes/filesafe-relay:stable
```

![Screen_5](https://user-images.githubusercontent.com/5485820/91877635-8d5df180-ec7e-11ea-9ca8-2d5762105763.png)

This setup is working with pCloud Webdav.

I only noticed just now this in the logs
`HTTP Origin header (http://127.0.0.1:45653) didn't match request.base_url (https://relay.mydomain.com)`

Do you know what it mean? Or how to fix it?

**Comment by BobWs** [comment] 2020-09-01 16:24
Fix it!

![Screen 6](https://user-images.githubusercontent.com/5485820/91879305-44a73800-ec80-11ea-8976-ea37cbbdc697.png)
Need to add this to the Reverse Proxy
`"X-Frame-Options" => "SAMEORIGIN"`

**Comment by BobWs** [comment] 2020-09-02 07:18
I'm sorry guess I spoke to soon, I'm still seeing these `HTTP Origin header (http://127.0.0.1:45653) didn't match request.base_url (https://relay.mydomain.com)` messages in the log file.

Any thoughts on how to solve it?

**Comment by BobWs** [comment] 2020-09-08 07:19
So now I’m also getting this message in the logs. Any idea how to solve this?

`HTTP Origin header (https://snotesextenions.netlify.app) didn't match request.base_url (https://relay.mydomain.com) | stdout`

**Comment by karolsojko** [comment] 2020-09-16 09:24
You might want to adjust your nginx config for that: https://github.com/rails/rails/issues/22965

**Comment by BobWs** [comment] 2020-09-16 17:37
I have adjusted the headers but I still get the error message in the logs:
`HTTP Origin header (https://snotesextenions.netlify.app) didn't match request.base_url (https://relay.mydomain.com) | stdout`

![FBB1BBA2-8F4A-41D9-8D8C-C2D796783C36](https://user-images.githubusercontent.com/5485820/93372214-dce21700-f853-11ea-8e19-d502e74894e1.jpeg)

Anything I’m doing wrong?

**Comment by mobitar** [comment] 2020-09-17 14:19
Not sure but I'd say double check the value for Access-Control-Allow-Headers. Maybe try a wildcard there.

**Comment by BobWs** [comment] 2020-09-17 19:31
> Not sure but I'd say double check the value for Access-Control-Allow-Headers. Maybe try a wildcard there.

Tried a wildcard but didn’t help, still have the same error message

**Comment by jrruethe** [comment] 2020-09-22 00:36
Hello, I am also trying to self-host the filesafe-relay and connect it to a webdav server (Nextcloud). It sounds like @BobWs has things working better than I do so far. Here is where I am at:

I have my Nextcloud running at "cloud.jrruethe.info" (This is internal to my network only). I have verified that I can connect to it properly by following the instructions [here](https://docs.nextcloud.com/server/16/user_manual/files/access_webdav.html), so I know that I have both the path and credentials correct:

![image](https://user-images.githubusercontent.com/4493273/93833593-a71ba480-fc3e-11ea-91a2-906b0a7f698f.png)

Next, I have the various Standard Notes pieces running in Docker containers (in Kubernetes). I am using all the official images [here](https://hub.docker.com/u/standardnotes), along with the self-hosted extensions [here](https://github.com/iganeshk/standardnotes-extensions). This all works well without issues.

The problem comes when I try to use the web client to hook up my Nextcloud webdav server into the Bold Editor via the filesafe-relay. First, I click "Add New" next to Integrations. This pops open the official link ([here](https://filesafe.standardnotes.org/)) which I just close out of, and instead open up my self-hosted filesafe-relay (at the address notes-filesafe.jrruethe.info).

This gives me the following. There seems to be no CSS, but other than that it generates invitation links:
![image](https://user-images.githubusercontent.com/4493273/93833975-ebf40b00-fc3f-11ea-8840-9b694ce9460b.png)
The CSS errors in the network monitor:
![image](https://user-images.githubusercontent.com/4493273/93834009-0a5a0680-fc40-11ea-97da-6dfeca5ddf63.png)

Pasting this invite code into the box works, and lets me add the integration. However, attempting to upload something fails. (The message on the UI is "Error Uploading File", but it disappears before I was able to get a screenshot):
![image](https://user-images.githubusercontent.com/4493273/93834166-7e94aa00-fc40-11ea-95e9-ffbee4ffe94f.png)

The network monitor shows some possible causes:
![image](https://user-images.githubusercontent.com/4493273/93834296-fb278880-fc40-11ea-9f48-7d5cfaaae7d7.png)

Specifically, the URL that is being posted to is:
https://notes-extensions.jrruethe.info/extensions/bold-editor/1.1.0/dist/filesafe-js/notes-filesafe.jrruethe.info/integrations/save-item
This is where I think the problem is. As far as I can tell, this URL isn't correct. I'm not exactly sure how this set up, but the "notes-filesafe.jrruethe.info" in the middle of this URL makes me think that the URL was built incorrectly or something. I don't really know Javascript so I am kinda stuck debugging this.

@BobWs (or anyone else), how were you able to get your filesafe-relay working? Which step am I missing? Thanks in advance for any help or tips!

The next thing I will try is building my own Docker image, instead of using the one from the hub.

**Comment by mobitar** [comment] 2020-09-22 13:14
> /extensions/bold-editor/1.1.0/dist/filesafe-js/null/integrations/save-item

This URL is incorrect. It looks like it's combining a local file path with a remote URL. Can you base64 decode your integration code, and make sure the URL embedded within is an absolute URL (should include https://)

**Comment by jrruethe** [comment] 2020-09-22 14:22
Ok, progress! I saw that the `relayUrl` was null, and after investigation it seems that my `HOST` environment variable was not actually set up like I thought. After fixing that, I get a new invitation code with the correct `relayUrl`, however now I have a different issue.

I un-base64'd the authorization piece, but it appears to be invalid base64 / incomplete json:

```
$ echo -n 'eyJzb3VyY2UiOiJ3ZWJkYXYiLCJhdXRob3JpemF0aW9uIjoiZXlKelpYSjJaWElpT2lKb2RIUndjem92TDJOc2IzVmtMbXB5Y25WbGRHaGxMbWx1Wm04dmNtVnRiM1JsXG5MbkJvY0M5a1lYWXZabWxzWlhNdmFuSnlkV1YwYUdVaUxDSjFjMlZ5Ym1GdFpTSTZJbXB5Y25WbGRHaGxcbklpd2ljR0Z6YzNkdmNtUWlPaUpBWVRBd01UZEZNamd3T1RnME15SXNJbVJwY2lJNklpOW1hV3hsYzJGbVxuWlNKOVxuIiwicmVsYXlVcmwiOiJodHRwczovL25vdGVzLWZpbGVzYWZlLmpycnVldGhlLmluZm8ifQ==' | base64 -d | jq .
{
  "source": "webdav",
  "authorization": "eyJzZXJ2ZXIiOiJodHRwczovL2Nsb3VkLmpycnVldGhlLmluZm8vcmVtb3Rl\nLnBocC9kYXYvZmlsZXMvanJydWV0aGUiLCJ1c2VybmFtZSI6ImpycnVldGhl\nIiwicGFzc3dvcmQiOiJAYTAwMTdFMjgwOTg0MyIsImRpciI6Ii9maWxlc2Fm\nZSJ9\n",
  "relayUrl": "https://notes-filesafe.jrruethe.info"
}

$ echo 'eyJzZXJ2ZXIiOiJodHRwczovL2Nsb3VkLmpycnVldGhlLmluZm8vcmVtb3Rl\nLnBocC9kYXYvZmlsZXMvanJydWV0aGUiLCJ1c2VybmFtZSI6ImpycnVldGhl\nIiwicGFzc3dvcmQiOiJAYTAwMTdFMjgwOTg0MyIsImRpciI6Ii9maWxlc2Fm\nZSJ9\n' | base64 -d
{"server":"https://cloud.jrruethe.info/remotebase64: invalid input
```

Do you know what would be causing it to get cut off like that? The path I am trying to enter into the server field is: https://cloud.jrruethe.info/remote.php/dav/files/jrruethe

As a side note, I also tried entering the path without the "https://", and I get the following:

```
$ echo -n 'eyJzZXJ2ZXIiOiJjbG91ZC5qcnJ1ZXRoZS5pbmZvL3JlbW90ZS5waHAvZGF2\nL2ZpbGVzL2pycnVldGhlIiwidXNlcm5hbWUiOiJqcnJ1ZXRoZSIsInBhc3N3\nb3JkIjoiQGEwMDE3RTI4MDk4NDMiLCJkaXIiOiIvZmlsZXNhZmUifQ==' | base64 -d
{"server":"cloud.jrruethe.info/remote.php/davbase64: invalid input
```

From these two experiments, it appears that the authorization token json is limited to 45 characters before base64? I feel like I am running into a very strange issue.

Thank you for any help!

**Comment by jrruethe** [comment] 2020-09-22 15:01
Ok, I'm making progress. I _thought_ I had the `HOST` environment variable set, however it was actually not set, so that was causing the `null`. (The `https://` is important! I also had that left off, and it caused different issues).

After fixing that, I managed to get further. Its still failing, but I can see the following in my Nextcloud logs when I attempt to do a file upload, so I think that the relay is doing its part. I just need to figure out what I am missing:

```
10.42.0.219 - jrruethe [22/Sep/2020:14:54:14 +0000] "PUT /remote.php/dav/files/filesafe/3581bfed-729b-44d7-b4cf-1e0906122efc.sf.json HTTP/1.1" 404 1527 "-" "Ruby"
```

That folder exists, as far as I can tell. Anyway, thanks for your help, I'll report back if I can get this bit working in case someone else stumbles upon issues like mine.

**Comment by jrruethe** [comment] 2020-09-22 15:54
Yahoo! It works! 

For anyone trying to get the self-hosted filesafe-relay working with Nextcloud, here was the trick:
- Make sure your `HOST` variable is set correctly to a DNS name that can be reached from your browser (ie: not an internal-to-docker ip:port) and make sure it has the `https://` on the front
- Make sure the `filesync` folder exists on your Nextcloud
- Set up the integration like this:
![image](https://user-images.githubusercontent.com/4493273/93906385-bdb70f80-fcc1-11ea-861f-bf22cc0a5cef.png)
Note that I had to prepend my username to the folder, and that it is NOT an absolute path.
After this, things work great!

**Comment by mobitar** [comment] 2020-09-22 15:55
Awesome, glad you got it working!

**Comment by BobWs** [comment] 2020-09-24 07:53
So I guess there is a routing problem with my self-host FileSafe Relay

I still keep getting these message in my logs. 
`HTTP Origin header (https://snotesextenions.netlify.app) didn't match request.base_url (https://relay.mydomain.com) | stdout` 

After further digging around and after an update of Standardnotes-web I have noticed that you now can preview the uploaded files.

![preview](https://user-images.githubusercontent.com/5485820/94115691-609a9580-fe4a-11ea-9b0b-33ce94d9549a.png)

When I press on preview the file is being download from my Webdav server and I'm being routed to my browser and I get an error the the file cannot be opened. This is because the redirected link doesn't match to my FileSafe-relay.

![Screen_Shot](https://user-images.githubusercontent.com/5485820/94116000-c424c300-fe4a-11ea-9662-8416dc355d5a.png)
As you can see the link above is the link to my standardnotes extensions.

`HTTP Origin header (https://snotesextenions.netlify.app) didn't match request.base_url (https://relay.mydomain.com) | stdout` 
`https://snotesextenions.netlify.app is my extensions link`
`https://relay.mydomain.com is my filesafe relay link`

I guess that is why I keep getting these error messages. But now the question is how do I fix this?

**Comment by BobWs** [comment] 2020-09-24 08:37
> Yahoo! It works!
> 
> For anyone trying to get the self-hosted filesafe-relay working with Nextcloud, here was the trick:
> 
>     * Make sure your `HOST` variable is set correctly to a DNS name that can be reached from your browser (ie: not an internal-to-docker ip:port) and make sure it has the `https://` on the front
> 
>     * Make sure the `filesafe` folder exists on your Nextcloud
> 
>     * Set up the integration like this:
>       ![image](https://user-images.githubusercontent.com/4493273/93906385-bdb70f80-fcc1-11ea-861f-bf22cc0a5cef.png)
>       Note that I had to prepend my username to the folder, and that it is NOT an absolute path.
>       After this, things work great!

@jrruethe Can you explain what you mean by `Host` "Make sure your HOST variable is set correctly to a DNS name..."
Is this the URL of your webdav or the URL of the filesafe-relay server?

**Comment by jrruethe** [comment] 2020-09-25 00:16
When I launch the filesafe-relay docker image, I set the "HOST" environment variable to the URL of the filesafe-relay server. I'm using Kubernetes, but the equivalent Docker run command would be something like:

```
docker run --rm -e HOST=https://notes-filesafe.example.com -p 3000:3000 standardnotes/filesafe-relay:4d2aff5cf7be34f9a27a515186d99bb20fe9a61b
```
(There are other env vars needed as well, like the secret_key_base, etc).

From what I can tell, this variable is used to populate the authorization token with details so that the web client knows where to find the filesafe-relay server.

**Comment by BobWs** [comment] 2020-09-25 08:25
> When I launch the filesafe-relay docker image, I set the "HOST" environment variable to the URL of the filesafe-relay server. I'm using Kubernetes, but the equivalent Docker run command would be something like:
> 
> ```
> docker run --rm -e HOST=https://notes-filesafe.example.com -p 3000:3000 standardnotes/filesafe-relay:4d2aff5cf7be34f9a27a515186d99bb20fe9a61b
> ```
> 
> (There are other env vars needed as well, like the secret_key_base, etc).
> 
> From what I can tell, this variable is used to populate the authorization token with details so that the web client knows where to find the filesafe-relay server.

Okay thanks for sharing, that is the same way I had set my filesafe-reay docker config. So I guess the error message I'm receiving isn't related to that.

**Closed** 2020-10-31 06:18 UTC
