### ISSUE TITLE
Floating keyboard on iPad prevents app from rendering

### ISSUE THREAD

**Issue by bryvin** [standardnotes/forum#808] opened 2019-12-12 20:08 UTC
User reported:

> When first time launching the app the screen is rendered white in case the iOS keyboard has been minified to the floating keyboard available since iPad OS. Opening some other app with a text input field, maximizing the keyboard and reopening S. Notes app “fixes” the issue.

**Comment by JaspalSuri** [comment] 2021-01-12 15:13
Closing this as I can't reproduce the issue in v3.5.16 (308) of our internal beta

**Closed by JaspalSuri** 2021-01-12 15:13 UTC
